import type { ToolMeta } from './types';

export const TOOLS: ToolMeta[] = [
  {
    slug:           'password-generator',
    name:           'Password Generator',
    tagline:        'Strong random passwords with custom settings',
    description:    'Create strong, cryptographically random passwords. No signup, nothing stored.',
    seoTitle:       'Free Password Generator — Strong & Secure Random Passwords | ToolKit',
    seoH1:          'Free Password Generator Online',
    seoDescription: 'Generate strong, random passwords instantly. Customize length, uppercase, symbols & more. 100% browser-based — your passwords never leave your device. Free, no signup.',
    category:       'Security',
    keywords:       ['password generator', 'strong password generator', 'random password generator', 'secure password generator', 'online password generator'],
    live:           true,
    featured:       true,
  },
  {
    slug:           'word-counter',
    name:           'Word Counter',
    tagline:        'Words, characters, sentences & reading time',
    description:    'Count words, characters, sentences, paragraphs and reading time instantly.',
    seoTitle:       'Free Word Counter Online — Count Words, Characters & Reading Time | ToolKit',
    seoH1:          'Free Word Counter Online',
    seoDescription: 'Count words, characters, sentences, paragraphs and reading time instantly. Includes keyword density and speaking time. Free online tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['word counter', 'word counter online', 'character counter', 'word count tool', 'reading time calculator', 'online word counter free'],
    live:           true,
  },
  {
    slug:           'lorem-ipsum',
    name:           'Lorem Ipsum Generator',
    tagline:        'Placeholder text for mockups & design',
    description:    'Generate Lorem Ipsum placeholder text by words, sentences, or paragraphs.',
    seoTitle:       'Free Lorem Ipsum Generator — Placeholder Text for Mockups | ToolKit',
    seoH1:          'Free Lorem Ipsum Generator Online',
    seoDescription: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences or paragraphs. Classic and random variants. Free online tool for designers and developers.',
    category:       'Text & Writing',
    keywords:       ['lorem ipsum generator', 'lorem ipsum', 'placeholder text generator', 'dummy text generator', 'lorem ipsum online'],
    live:           true,
  },
  {
    slug:           'uuid-generator',
    name:           'UUID Generator',
    tagline:        'Generate v4 UUIDs instantly',
    description:    'Generate cryptographically random UUID v4 identifiers in one click.',
    seoTitle:       'Free UUID Generator Online — Generate v4 UUIDs Instantly | ToolKit',
    seoH1:          'Free UUID Generator Online',
    seoDescription: 'Generate cryptographically random UUID v4 identifiers instantly. Generate 1–50 UUIDs at once, copy all with one click. Free, browser-based, no signup.',
    category:       'Developer Tools',
    keywords:       ['uuid generator', 'uuid generator online', 'unique id generator', 'guid generator', 'random uuid', 'uuid v4 generator'],
    live:           true,
  },
  {
    slug:           'base64',
    name:           'Base64 Encoder / Decoder',
    tagline:        'Encode or decode Base64 strings instantly',
    description:    'Encode text to Base64 or decode Base64 strings back to plain text.',
    seoTitle:       'Free Base64 Encoder & Decoder Online — Encode & Decode Instantly | ToolKit',
    seoH1:          'Free Base64 Encoder & Decoder Online',
    seoDescription: 'Encode text to Base64 or decode Base64 strings back to plain text instantly. Supports UTF-8. Free online Base64 converter — no signup, works in your browser.',
    category:       'Developer Tools',
    keywords:       ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter online', 'encode to base64'],
    live:           true,
  },
  {
    slug:           'json-formatter',
    name:           'JSON Formatter',
    tagline:        'Prettify, minify & validate JSON',
    description:    'Format, beautify, minify and validate JSON data online.',
    seoTitle:       'Free JSON Formatter Online — Prettify, Minify & Validate JSON | ToolKit',
    seoH1:          'Free JSON Formatter & Validator Online',
    seoDescription: 'Format, beautify, minify and validate JSON data instantly. Choose 2 or 4-space indentation. Highlights syntax errors. Free online JSON formatter — no signup.',
    category:       'Developer Tools',
    keywords:       ['json formatter', 'json formatter online', 'json beautifier', 'json validator', 'json prettify', 'format json online', 'json minifier'],
    live:           true,
  },
  {
    slug:           'url-encoder',
    name:           'URL Encoder / Decoder',
    tagline:        'Encode and decode URLs instantly',
    description:    'Encode special characters in URLs or decode percent-encoded strings.',
    seoTitle:       'Free URL Encoder & Decoder Online — Percent Encode / Decode | ToolKit',
    seoH1:          'Free URL Encoder & Decoder Online',
    seoDescription: 'Encode special characters in URLs or decode percent-encoded strings instantly. Swap encode/decode with one click. Free online URL converter — no signup required.',
    category:       'Developer Tools',
    keywords:       ['url encoder', 'url decoder', 'url encode online', 'url decode online', 'percent encoding', 'urlencode', 'url encoding tool'],
    live:           true,
  },
  {
    slug:           'hash-generator',
    name:           'Hash Generator',
    tagline:        'SHA-1, SHA-256, SHA-384, SHA-512 hashes',
    description:    'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text.',
    seoTitle:       'Free Hash Generator Online — SHA-256, SHA-512, SHA-1 | ToolKit',
    seoH1:          'Free Hash Generator Online',
    seoDescription: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text instantly. All hashing runs in your browser via Web Crypto API. Free, no signup, no data stored.',
    category:       'Security',
    keywords:       ['hash generator', 'sha256 generator', 'sha-256 online', 'sha512 generator', 'sha1 hash online', 'text hash generator', 'hash string online'],
    live:           true,
  },
  {
    slug:           'case-converter',
    name:           'Case Converter',
    tagline:        'UPPER, lower, Title, camelCase, snake_case & more',
    description:    'Convert text between uppercase, lowercase, camelCase, snake_case, kebab-case and more.',
    seoTitle:       'Free Case Converter Online — camelCase, snake_case, Title Case & More | ToolKit',
    seoH1:          'Free Case Converter Online',
    seoDescription: 'Convert text to uppercase, lowercase, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE instantly. Free online text case converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['case converter', 'text case converter', 'camelcase converter', 'snake case converter', 'uppercase lowercase converter', 'title case converter', 'convert to camelcase'],
    live:           true,
  },
  {
    slug:           'markdown-editor',
    name:           'Markdown Editor',
    tagline:        'Write and preview Markdown live',
    description:    'Write Markdown with live HTML preview. Copy output as HTML.',
    seoTitle:       'Free Online Markdown Editor — Live Preview & HTML Export | ToolKit',
    seoH1:          'Free Online Markdown Editor with Live Preview',
    seoDescription: 'Write Markdown with instant live preview. Supports headings, bold, italic, code blocks, lists, links and tables. Export as HTML. Free online Markdown editor — no signup.',
    category:       'Text & Writing',
    keywords:       ['markdown editor', 'markdown editor online', 'markdown preview', 'online markdown editor', 'markdown to html', 'live markdown editor'],
    live:           true,
  },
  {
    slug:           'color-palette',
    name:           'Color Palette Generator',
    tagline:        'Generate harmonious color palettes',
    description:    'Generate harmonious color palettes with 7 harmony modes. Copy HEX, RGB, HSL or CSS.',
    seoTitle:       'Free Color Palette Generator — Analogous, Complementary & More | ToolKit',
    seoH1:          'Free Color Palette Generator Online',
    seoDescription: 'Generate beautiful color palettes instantly. Choose analogous, complementary, triadic, tetradic, monochromatic and more. Copy HEX, RGB, HSL or CSS variables. Free, no signup.',
    category:       'Design',
    keywords:       ['color palette generator', 'color palette generator online', 'color scheme generator', 'color picker online', 'complementary color generator', 'color harmony tool'],
    live:           true,
  },
  {
    slug:           'username-generator',
    name:           'Username Generator',
    tagline:        'Creative usernames for social media & gaming',
    description:    'Generate unique usernames for social media, gaming and professional accounts.',
    seoTitle:       'Free Username Generator — Creative Usernames for Social Media & Gaming | ToolKit',
    seoH1:          'Free Username Generator Online',
    seoDescription: 'Generate creative, unique usernames for social media, gaming, Discord, Twitch and more. Choose fun, professional, gamer or minimal styles. Free online username generator.',
    category:       'Design',
    keywords:       ['username generator', 'username generator online', 'random username generator', 'nickname generator', 'gamertag generator', 'discord username generator'],
    live:           true,
  },
];

/* ── Helpers ──────────────────────────────────────────── */
export const getLiveTools  = () => TOOLS.filter(t => t.live);
export const getSoonTools  = () => TOOLS.filter(t => !t.live);
export const getFeatured   = () => TOOLS.find(t => t.featured);
export const getBySlug     = (slug: string) => TOOLS.find(t => t.slug === slug);
export const getLiveSlugs  = () => getLiveTools().map(t => t.slug);

export const getByCategory = () => {
  const map = new Map<string, ToolMeta[]>();
  for (const tool of TOOLS) {
    if (!map.has(tool.category)) map.set(tool.category, []);
    map.get(tool.category)!.push(tool);
  }
  return map;
};