import type { ToolMeta } from './types';
import { variants as passwordGeneratorVariants } from '@/tools/password-generator/variants';

export const TOOLS: ToolMeta[] = [
  {
    slug:           'password-generator',
    name:           'Password Generator',
    tagline:        'Strong random passwords with custom settings',
    description:    'Create strong, cryptographically random passwords. No signup, nothing stored.',
    seoTitle:       'Free Password Generator — Strong & Secure Random Passwords | ToolKit',
    seoH1:          'Free Password Generator Online',
    seoDescription: 'Generate strong, random passwords instantly. Customize length, uppercase, symbols & more. 100% browser-based — your passwords never leave your device. Free, no signup.',
    category:       'Security',
    keywords:       ['password generator', 'strong password generator', 'random password generator', 'secure password generator', 'online password generator'],
    live:           true,
    featured:       true,
    variants:       passwordGeneratorVariants
  },
  {
    slug:           'word-counter',
    name:           'Word Counter',
    tagline:        'Words, characters, sentences & reading time',
    description:    'Count words, characters, sentences, paragraphs and reading time instantly.',
    seoTitle:       'Free Word Counter Online — Count Words, Characters & Reading Time | ToolKit',
    seoH1:          'Free Word Counter Online',
    seoDescription: 'Count words, characters, sentences, paragraphs and reading time instantly. Includes keyword density and speaking time. Free online tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['word counter', 'word counter online', 'character counter', 'word count tool', 'reading time calculator', 'online word counter free'],
    live:           true,
  },
  {
    slug:           'lorem-ipsum',
    name:           'Lorem Ipsum Generator',
    tagline:        'Placeholder text for mockups & design',
    description:    'Generate Lorem Ipsum placeholder text by words, sentences, or paragraphs.',
    seoTitle:       'Free Lorem Ipsum Generator — Placeholder Text for Mockups | ToolKit',
    seoH1:          'Free Lorem Ipsum Generator Online',
    seoDescription: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences or paragraphs. Classic and random variants. Free online tool for designers and developers.',
    category:       'Text & Writing',
    keywords:       ['lorem ipsum generator', 'lorem ipsum', 'placeholder text generator', 'dummy text generator', 'lorem ipsum online'],
    live:           true,
  },
  {
    slug:           'uuid-generator',
    name:           'UUID Generator',
    tagline:        'Generate v4 UUIDs instantly',
    description:    'Generate cryptographically random UUID v4 identifiers in one click.',
    seoTitle:       'Free UUID Generator Online — Generate v4 UUIDs Instantly | ToolKit',
    seoH1:          'Free UUID Generator Online',
    seoDescription: 'Generate cryptographically random UUID v4 identifiers instantly. Generate 1–50 UUIDs at once, copy all with one click. Free, browser-based, no signup.',
    category:       'Developer Tools',
    keywords:       ['uuid generator', 'uuid generator online', 'unique id generator', 'guid generator', 'random uuid', 'uuid v4 generator'],
    live:           true,
  },
  {
    slug:           'base64',
    name:           'Base64 Encoder / Decoder',
    tagline:        'Encode or decode Base64 strings instantly',
    description:    'Encode text to Base64 or decode Base64 strings back to plain text.',
    seoTitle:       'Free Base64 Encoder & Decoder Online — Encode & Decode Instantly | ToolKit',
    seoH1:          'Free Base64 Encoder & Decoder Online',
    seoDescription: 'Encode text to Base64 or decode Base64 strings back to plain text instantly. Supports UTF-8. Free online Base64 converter — no signup, works in your browser.',
    category:       'Developer Tools',
    keywords:       ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter online', 'encode to base64'],
    live:           true,
  },
  {
    slug:           'json-formatter',
    name:           'JSON Formatter',
    tagline:        'Prettify, minify & validate JSON',
    description:    'Format, beautify, minify and validate JSON data online.',
    seoTitle:       'Free JSON Formatter Online — Prettify, Minify & Validate JSON | ToolKit',
    seoH1:          'Free JSON Formatter & Validator Online',
    seoDescription: 'Format, beautify, minify and validate JSON data instantly. Choose 2 or 4-space indentation. Highlights syntax errors. Free online JSON formatter — no signup.',
    category:       'Developer Tools',
    keywords:       ['json formatter', 'json formatter online', 'json beautifier', 'json validator', 'json prettify', 'format json online', 'json minifier'],
    live:           true,
  },
  {
    slug:           'url-encoder',
    name:           'URL Encoder / Decoder',
    tagline:        'Encode and decode URLs instantly',
    description:    'Encode special characters in URLs or decode percent-encoded strings.',
    seoTitle:       'Free URL Encoder & Decoder Online — Percent Encode / Decode | ToolKit',
    seoH1:          'Free URL Encoder & Decoder Online',
    seoDescription: 'Encode special characters in URLs or decode percent-encoded strings instantly. Swap encode/decode with one click. Free online URL converter — no signup required.',
    category:       'Developer Tools',
    keywords:       ['url encoder', 'url decoder', 'url encode online', 'url decode online', 'percent encoding', 'urlencode', 'url encoding tool'],
    live:           true,
  },
  {
    slug:           'hash-generator',
    name:           'Hash Generator',
    tagline:        'SHA-1, SHA-256, SHA-384, SHA-512 hashes',
    description:    'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text.',
    seoTitle:       'Free Hash Generator Online — SHA-256, SHA-512, SHA-1 | ToolKit',
    seoH1:          'Free Hash Generator Online',
    seoDescription: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text instantly. All hashing runs in your browser via Web Crypto API. Free, no signup, no data stored.',
    category:       'Security',
    keywords:       ['hash generator', 'sha256 generator', 'sha-256 online', 'sha512 generator', 'sha1 hash online', 'text hash generator', 'hash string online'],
    live:           true,
  },
  {
    slug:           'case-converter',
    name:           'Case Converter',
    tagline:        'UPPER, lower, Title, camelCase, snake_case & more',
    description:    'Convert text between uppercase, lowercase, camelCase, snake_case, kebab-case and more.',
    seoTitle:       'Free Case Converter Online — camelCase, snake_case, Title Case & More | ToolKit',
    seoH1:          'Free Case Converter Online',
    seoDescription: 'Convert text to uppercase, lowercase, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE instantly. Free online text case converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['case converter', 'text case converter', 'camelcase converter', 'snake case converter', 'uppercase lowercase converter', 'title case converter', 'convert to camelcase'],
    live:           true,
  },
  {
    slug:           'markdown-editor',
    name:           'Markdown Editor',
    tagline:        'Write and preview Markdown live',
    description:    'Write Markdown with live HTML preview. Copy output as HTML.',
    seoTitle:       'Free Online Markdown Editor — Live Preview & HTML Export | ToolKit',
    seoH1:          'Free Online Markdown Editor with Live Preview',
    seoDescription: 'Write Markdown with instant live preview. Supports headings, bold, italic, code blocks, lists, links and tables. Export as HTML. Free online Markdown editor — no signup.',
    category:       'Text & Writing',
    keywords:       ['markdown editor', 'markdown editor online', 'markdown preview', 'online markdown editor', 'markdown to html', 'live markdown editor'],
    live:           true,
  },
  {
    slug:           'color-palette',
    name:           'Color Palette Generator',
    tagline:        'Generate harmonious color palettes',
    description:    'Generate harmonious color palettes with 7 harmony modes. Copy HEX, RGB, HSL or CSS.',
    seoTitle:       'Free Color Palette Generator — Analogous, Complementary & More | ToolKit',
    seoH1:          'Free Color Palette Generator Online',
    seoDescription: 'Generate beautiful color palettes instantly. Choose analogous, complementary, triadic, tetradic, monochromatic and more. Copy HEX, RGB, HSL or CSS variables. Free, no signup.',
    category:       'Design',
    keywords:       ['color palette generator', 'color palette generator online', 'color scheme generator', 'color picker online', 'complementary color generator', 'color harmony tool'],
    live:           true,
  },
  {
    slug:           'username-generator',
    name:           'Username Generator',
    tagline:        'Creative usernames for social media & gaming',
    description:    'Generate unique usernames for social media, gaming and professional accounts.',
    seoTitle:       'Free Username Generator — Creative Usernames for Social Media & Gaming | ToolKit',
    seoH1:          'Free Username Generator Online',
    seoDescription: 'Generate creative, unique usernames for social media, gaming, Discord, Twitch and more. Choose fun, professional, gamer or minimal styles. Free online username generator.',
    category:       'Design',
    keywords:       ['username generator', 'username generator online', 'random username generator', 'nickname generator', 'gamertag generator', 'discord username generator'],
    live:           true,
  },

  /* ── Coming soon — Security ─────────────────────────── */
  {
    slug:           'bcrypt-generator',
    name:           'Bcrypt Generator',
    tagline:        'Hash and verify passwords with bcrypt',
    description:    'Generate bcrypt hashes from passwords and verify them. Adjustable cost factor.',
    seoTitle:       'Free Bcrypt Generator & Verifier Online | ToolKit',
    seoH1:          'Free Bcrypt Password Hash Generator',
    seoDescription: 'Generate and verify bcrypt password hashes online. Choose cost factor 4–12. Free browser-based bcrypt tool — no data sent to any server.',
    category:       'Security',
    keywords:       ['bcrypt generator', 'bcrypt hash online', 'bcrypt password', 'bcrypt verifier'],
    live:           false,
  },
  {
    slug:           'jwt-decoder',
    name:           'JWT Decoder',
    tagline:        'Decode and inspect JWT tokens',
    description:    'Decode JWT tokens and inspect header, payload and signature. No verification needed.',
    seoTitle:       'Free JWT Decoder Online — Decode & Inspect JSON Web Tokens | ToolKit',
    seoH1:          'Free JWT Decoder Online',
    seoDescription: 'Decode and inspect JWT tokens instantly. View header, payload and signature. Verify expiration. Free online JWT decoder — no data sent to servers.',
    category:       'Security',
    keywords:       ['jwt decoder', 'jwt decoder online', 'decode jwt token', 'json web token decoder', 'jwt inspector'],
    live:           false,
  },
  {
    slug:           'qr-code-generator',
    name:           'QR Code Generator',
    tagline:        'Generate QR codes for URLs and text',
    description:    'Generate QR codes for any URL, text, WiFi, email or phone. Download as PNG or SVG. No watermark, no signup.',
    seoTitle:       'Free QR Code Generator — Create QR Codes Instantly, No Signup | ToolKit',
    seoH1:          'Free QR Code Generator Online',
    seoDescription: 'Generate QR codes for URLs, WiFi, email, phone and more. Download as PNG or SVG. Customize colors and size. 100% free, no watermark, no signup — works in your browser.',
    category:       'Security',
    keywords:       ['qr code generator', 'qr code generator online', 'free qr code generator', 'create qr code', 'qr generator', 'qr code maker', 'qr code creator', 'wifi qr code generator'],
    live:           true,
  },

  /* ── Coming soon — Text & Writing ───────────────────── */
  {
    slug:           'text-diff',
    name:           'Text Diff Checker',
    tagline:        'Compare two texts and highlight differences',
    description:    'Compare two blocks of text and see additions, deletions and changes highlighted.',
    seoTitle:       'Free Text Diff Checker Online — Compare Two Texts | ToolKit',
    seoH1:          'Free Text Diff Checker Online',
    seoDescription: 'Compare two texts and highlight differences instantly. See added, removed and changed lines color-coded. Free online diff tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['text diff checker', 'diff checker online', 'compare two texts', 'text compare online', 'text difference tool'],
    live:           false,
  },
  {
    slug:           'reading-time-calculator',
    name:           'Reading Time Calculator',
    tagline:        'Estimate reading time from word count',
    description:    'Calculate reading and speaking time from any text or word count.',
    seoTitle:       'Free Reading Time Calculator — Estimate Read Time Online | ToolKit',
    seoH1:          'Free Reading Time Calculator Online',
    seoDescription: 'Calculate how long it takes to read any text. Set your reading speed, get reading and speaking time estimates. Free online reading time calculator.',
    category:       'Text & Writing',
    keywords:       ['reading time calculator', 'read time estimator', 'words per minute calculator', 'article reading time'],
    live:           false,
  },
  {
    slug:           'random-text-generator',
    name:           'Random Text Generator',
    tagline:        'Generate random words, sentences and paragraphs',
    description:    'Generate random English words, sentences or paragraphs for testing.',
    seoTitle:       'Free Random Text Generator Online — Words, Sentences & Paragraphs | ToolKit',
    seoH1:          'Free Random Text Generator Online',
    seoDescription: 'Generate random words, sentences or paragraphs instantly. Choose length and style. Great for testing, mockups and development. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['random text generator', 'random word generator', 'random sentence generator', 'random paragraph generator'],
    live:           false,
  },
  {
    slug:           'csv-to-json',
    name:           'CSV to JSON Converter',
    tagline:        'Convert CSV data to JSON format',
    description:    'Paste CSV data and convert it to JSON instantly. Supports headers.',
    seoTitle:       'Free CSV to JSON Converter Online — Convert CSV Instantly | ToolKit',
    seoH1:          'Free CSV to JSON Converter Online',
    seoDescription: 'Convert CSV to JSON format instantly. Paste your CSV data, choose options, and get clean JSON output. Free online CSV to JSON converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['csv to json', 'csv to json converter', 'convert csv to json online', 'csv json converter'],
    live:           false,
  },

  /* ── Coming soon — Developer Tools ─────────────────── */
  {
    slug:           'regex-tester',
    name:           'Regex Tester',
    tagline:        'Test and debug regular expressions live',
    description:    'Test regular expressions with live match highlighting. Supports JavaScript and Python.',
    seoTitle:       'Free Regex Tester Online — Test & Debug Regular Expressions | ToolKit',
    seoH1:          'Free Regex Tester Online',
    seoDescription: 'Test and debug regular expressions with live match highlighting. Supports JavaScript regex flags. See matches, groups and captures instantly. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['regex tester', 'regex tester online', 'regular expression tester', 'regex checker', 'regex debugger online'],
    live:           true,
  },
  {
    slug:           'timestamp-converter',
    name:           'Timestamp Converter',
    tagline:        'Convert Unix timestamps to human-readable dates',
    description:    'Convert Unix timestamps to dates and back. Supports seconds and milliseconds.',
    seoTitle:       'Free Unix Timestamp Converter Online — Epoch to Date | ToolKit',
    seoH1:          'Free Unix Timestamp Converter Online',
    seoDescription: 'Convert Unix/epoch timestamps to human-readable dates and back. Supports seconds and milliseconds. Shows current timestamp live. Free online timestamp converter.',
    category:       'Developer Tools',
    keywords:       ['timestamp converter', 'unix timestamp converter', 'epoch converter', 'epoch to date', 'timestamp to date online'],
    live:           false,
  },
  {
    slug:           'cron-generator',
    name:           'Cron Expression Generator',
    tagline:        'Build and validate cron job schedules',
    description:    'Generate cron expressions visually and see next execution times in plain English.',
    seoTitle:       'Free Cron Expression Generator & Validator Online | ToolKit',
    seoH1:          'Free Cron Expression Generator Online',
    seoDescription: 'Build cron expressions visually, validate syntax and see next 10 run times in plain English. Free cron job generator — no signup, works in browser.',
    category:       'Developer Tools',
    keywords:       ['cron generator', 'cron expression generator', 'cron job generator online', 'crontab generator', 'cron expression validator'],
    live:           false,
  },
  {
    slug:           'css-minifier',
    name:           'CSS Minifier',
    tagline:        'Minify and beautify CSS code',
    description:    'Minify or beautify CSS code. Remove comments, whitespace and optimize output.',
    seoTitle:       'Free CSS Minifier & Beautifier Online — Compress CSS | ToolKit',
    seoH1:          'Free CSS Minifier & Beautifier Online',
    seoDescription: 'Minify CSS to reduce file size or beautify compressed CSS for readability. Removes comments and whitespace. Free online CSS minifier — no signup.',
    category:       'Developer Tools',
    keywords:       ['css minifier', 'css minifier online', 'minify css', 'css compressor', 'css beautifier online'],
    live:           false,
  },
  {
    slug:           'html-entities',
    name:           'HTML Entities Encoder',
    tagline:        'Encode and decode HTML entities',
    description:    'Encode special characters as HTML entities or decode HTML entities back to text.',
    seoTitle:       'Free HTML Entities Encoder & Decoder Online | ToolKit',
    seoH1:          'Free HTML Entities Encoder & Decoder',
    seoDescription: 'Encode special characters as HTML entities or decode HTML entities back to plain text. Free online HTML entity encoder — no signup, instant results.',
    category:       'Developer Tools',
    keywords:       ['html entities encoder', 'html entity decoder', 'html encode online', 'html escape online', 'html entities converter'],
    live:           false,
  },

  /* ── Value Converter ───────────────────────────────── */
  {
    slug:           'time-converter',
    name:           'Time Converter',
    tagline:        'Convert seconds, minutes, hours, days, weeks, years',
    description:    'Convert any time value between seconds, minutes, hours, days, weeks, months and years instantly.',
    seoTitle:       'Free Time Converter Online — Seconds to Days, Weeks, Years | ToolKit',
    seoH1:          'Free Time Converter Online',
    seoDescription: 'Convert time values instantly between seconds, minutes, hours, days, weeks, months and years. Enter any value and get all units at once. Free, browser-based, no signup.',
    category:       'Value Converter',
    keywords:       ['time converter', 'seconds to days', 'seconds to years', 'days to seconds', 'time unit converter', 'convert seconds to hours', 'convert days to weeks'],
    live:           true,
  },

  /* ── Coming soon — Design ───────────────────────────── */
  {
    slug:           'color-converter',
    name:           'Color Converter',
    tagline:        'Convert between HEX, RGB, HSL, HSV and CMYK',
    description:    'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Live preview, CSS output, one-click copy.',
    seoTitle:       'Free Color Converter — HEX to RGB, HSL, CMYK & More | ToolKit',
    seoH1:          'Free Color Converter Online',
    seoDescription: 'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Get CSS-ready output, live color preview, and one-click copy. Free, browser-based, no signup.',
    category:       'Design',
    keywords:       ['color converter', 'hex to rgb', 'rgb to hex', 'hsl to hex', 'hex to hsl', 'rgb to hsl', 'cmyk to rgb', 'color format converter', 'css color converter'],
    live:           true,
  },
  {
    slug:           'gradient-generator',
    name:           'CSS Gradient Generator',
    tagline:        'Create CSS gradients with live preview',
    description:    'Generate linear and radial CSS gradients visually. Copy the CSS output.',
    seoTitle:       'Free CSS Gradient Generator Online — Linear & Radial Gradients | ToolKit',
    seoH1:          'Free CSS Gradient Generator Online',
    seoDescription: 'Create beautiful linear and radial CSS gradients with live preview. Adjust colors, angle and stops. Copy the CSS output. Free online gradient generator.',
    category:       'Design',
    keywords:       ['css gradient generator', 'gradient generator online', 'linear gradient generator', 'css gradient maker', 'gradient css tool'],
    live:           false,
  },
  {
    slug:           'box-shadow-generator',
    name:           'Box Shadow Generator',
    tagline:        'Create CSS box shadows with live preview',
    description:    'Generate CSS box-shadow values visually with real-time preview.',
    seoTitle:       'Free CSS Box Shadow Generator Online — Live Preview | ToolKit',
    seoH1:          'Free CSS Box Shadow Generator Online',
    seoDescription: 'Create CSS box shadows visually with live preview. Adjust blur, spread, color and inset. Copy the CSS. Free online box shadow generator — no signup.',
    category:       'Design',
    keywords:       ['box shadow generator', 'css box shadow generator', 'box shadow css online', 'css shadow tool'],
    live:           false,
  },
  {
    slug:           'favicon-generator',
    name:           'Favicon Generator',
    tagline:        'Generate favicons from text or emoji',
    description:    'Create favicons from text, emoji or simple icons. Download as ICO and PNG.',
    seoTitle:       'Free Favicon Generator Online — Create Favicons from Text & Emoji | ToolKit',
    seoH1:          'Free Favicon Generator Online',
    seoDescription: 'Generate favicons from text, letters or emoji. Download as ICO (16×16, 32×32) and PNG (192×192). Free online favicon generator — no signup, instant download.',
    category:       'Design',
    keywords:       ['favicon generator', 'favicon generator online', 'create favicon', 'favicon maker', 'free favicon generator'],
    live:           false,
  },
];

/* ── Helpers ──────────────────────────────────────────── */
export const getLiveTools  = () => TOOLS.filter(t => t.live);
export const getSoonTools  = () => TOOLS.filter(t => !t.live);
export const getFeatured   = () => TOOLS.find(t => t.featured);
export const getBySlug     = (slug: string) => TOOLS.find(t => t.slug === slug);
export const getLiveSlugs  = () => getLiveTools().map(t => t.slug);

export const getVariant = (toolSlug: string, variantSlug: string) => {
  const tool = getBySlug(toolSlug);
  return tool?.variants?.find(v => v.slug === variantSlug) ?? null;
};

export const getAllVariantPaths = () => {
  const paths: { params: { slug: string; variant: string } }[] = [];
  for (const tool of getLiveTools()) {
    for (const v of tool.variants ?? []) {
      paths.push({ params: { slug: tool.slug, variant: v.slug } });
    }
  }
  return paths;
};

export const getByCategory = () => {
  const map = new Map<string, ToolMeta[]>();
  for (const tool of TOOLS) {
    if (!map.has(tool.category)) map.set(tool.category, []);
    map.get(tool.category)!.push(tool);
  }
  return map;
};