import type { ToolMeta } from './types';

export const TOOLS: ToolMeta[] = [
  {
    slug:           'password-generator',
    name:           'Password Generator',
    tagline:        'Strong random passwords with custom settings',
    description:    'Create strong, cryptographically random passwords. No signup, nothing stored.',
    seoTitle:       'Free Password Generator — Strong & Secure Random Passwords | ToolKit',
    seoH1:          'Free Password Generator Online',
    seoDescription: 'Generate strong, random passwords instantly. Customize length, uppercase, symbols & more. 100% browser-based — your passwords never leave your device. Free, no signup.',
    category:       'Security',
    keywords:       ['password generator', 'strong password generator', 'random password generator', 'secure password generator', 'online password generator'],
    live:           true,
    featured:       true,
    variants: [
      {
        slug:           'for-wifi',
        seoTitle:       'WiFi Password Generator — Strong Passwords for Your Router | ToolKit',
        seoH1:          'WiFi Password Generator',
        seoDescription: 'Generate a strong, random WiFi password instantly. WPA2/WPA3 supports up to 63 characters — use all types for maximum security. Free, browser-based, no signup.',
        intro:          'A WiFi password is one of the most important passwords in your home or office — it controls access to your entire network and every device on it. WPA2 and WPA3, the current wireless security standards, support passwords up to 63 characters. Unlike account passwords that need to be typed daily, a WiFi password is entered once per device, which means you can make it as long and random as possible without any usability penalty. This generator defaults to 20 characters with all character types enabled — the recommended setting for a residential or small business router. Avoid common mistakes like using your address, phone number, or a simple word. A strong WiFi password prevents unauthorized access, protects your bandwidth, and stops attackers from using your network as a vector for other attacks.',
        faq: [
          { q: 'How long should a WiFi password be?', a: 'WPA2 and WPA3 support 8–63 characters. Use at least 16 characters for a home network and 20+ for a business network. Longer is always better — you only need to type it once per device.' },
          { q: 'What characters are allowed in a WiFi password?', a: 'WPA2/WPA3 passwords can include uppercase letters, lowercase letters, digits, and most special characters. Avoid characters that may cause issues on some devices: single quotes, double quotes, and backslashes.' },
          { q: 'Do I need to change my WiFi password regularly?', a: 'Only if you suspect a breach — for example, after a guest has used it and you want to revoke access, or after a device has been compromised. Unlike account passwords, WiFi passwords do not need routine rotation.' },
          { q: 'What is the difference between WPA2 and WPA3?', a: 'WPA3 is the newer standard with stronger encryption (SAE instead of PSK) and protection against brute-force attacks. If your router supports WPA3, enable it. If not, WPA2-AES is still considered secure with a strong password.' },
          { q: 'Can my neighbors crack my WiFi password?', a: 'A 16+ character random password with mixed character types would take billions of years to crack with current hardware. The real risk is password reuse or easy-to-guess passwords — not brute force against a strong random one.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: true },
      },
      {
        slug:           'for-testing',
        seoTitle:       'Password Generator for Testing — Realistic Test Passwords | ToolKit',
        seoH1:          'Password Generator for Testing & Development',
        seoDescription: 'Generate realistic test passwords for development and QA. Configurable length and character sets. Browser-based, no data stored. Free, no signup.',
        intro:          'When building or testing authentication systems, the passwords you use in your test data matter more than most developers realize. Using "password", "test123", or "admin" in test accounts creates two problems: it trains muscle memory for weak passwords, and it risks those credentials leaking into production via database seeds or exported fixtures. A realistic test password — 12-16 characters with mixed types — also validates that your input fields, password strength meters, and hashing functions handle real-world values correctly. Truncation bugs, encoding issues with special characters, and bcrypt length limits (72 bytes) are all easier to catch with realistic passwords. This generator lets you configure exactly the character set and length you need for your test scenarios, from simple alphanumeric passwords to full-complexity strings that stress-test your validation logic.',
        faq: [
          { q: 'What password length should I use for test data?', a: 'Match what real users will create — 12-20 characters covers the realistic range. Also test edge cases: the minimum allowed length (usually 8), the maximum (often 64 or 128), and lengths that would exceed bcrypt\'s 72-byte limit.' },
          { q: 'Should test passwords include special characters?', a: 'Yes — special characters expose encoding bugs, escaping issues in SQL/HTML, and validation logic errors. Test with characters like !@#$%^&* and also with edge cases like quotes and backslashes.' },
          { q: 'Can I use the same test password across environments?', a: 'Use different passwords for development, staging, and production test accounts. Never seed a production database with the same credentials used in development.' },
          { q: 'What is bcrypt\'s 72-byte password limit?', a: 'bcrypt truncates input at 72 bytes. This means passwords longer than ~72 ASCII characters are silently treated as identical after that point. If your app uses bcrypt, test this boundary explicitly.' },
          { q: 'How do I generate bulk test passwords?', a: 'Click the generator multiple times, or use the copy button for each. For programmatic bulk generation, use crypto.randomUUID() for simple tokens or the Web Crypto API\'s getRandomValues() for full password generation in Node.js or the browser.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
      },
      {
        slug:           'strong-20-characters',
        seoTitle:       'Strong 20 Character Password Generator — High-Security Passwords | ToolKit',
        seoH1:          '20 Character Password Generator',
        seoDescription: 'Generate strong 20-character passwords instantly. 20 characters with mixed types gives ~131 bits of entropy — effectively uncrackable. Free, browser-based, no signup.',
        intro:          'A 20-character random password with uppercase letters, lowercase letters, numbers, and symbols provides approximately 131 bits of entropy. To put that in perspective: even if every computer on Earth attempted a trillion guesses per second, cracking it would take longer than the current age of the universe. The NIST Digital Identity Guidelines recommend at least 15 characters for general accounts — 20 characters gives you a significant safety margin above that threshold. Twenty characters is also the sweet spot between security and usability: long enough to be essentially uncrackable, short enough to copy-paste or type without excessive effort. This generator defaults to exactly 20 characters with all four character sets enabled, producing the highest-entropy output this length allows.',
        faq: [
          { q: 'How secure is a 20-character password?', a: 'A 20-character password using all character types has approximately 131 bits of entropy. At 10 billion guesses per second (a high-end GPU attack), cracking it would take around 10²⁰ years — effectively impossible with any foreseeable technology.' },
          { q: 'Is 20 characters enough for all accounts?', a: 'Yes — 20 characters exceeds the NIST recommendation of 15 characters and is sufficient for any current use case including banking, email, and cloud storage. For extremely sensitive accounts, you can go up to 32 or 64 characters.' },
          { q: 'Do all websites accept 20-character passwords?', a: 'Most modern websites accept passwords up to 64 characters (NIST recommendation for maximum length). Some older systems have lower limits — typically 32 or 20 characters. If a site rejects your password, try reducing to 16 characters first.' },
          { q: 'What is the entropy of a 20-character password?', a: 'With 95 printable ASCII characters available (uppercase, lowercase, digits, symbols), each character contributes log₂(95) ≈ 6.57 bits of entropy. 20 characters × 6.57 = ~131 bits total.' },
          { q: 'Should I use 20 characters or a passphrase?', a: 'A 20-character random password is stronger per character but impossible to memorize. Use it for any password stored in a manager. Use a passphrase only for the few passwords you must type manually — like your password manager master password.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: true },
      },
      {
        slug:           'no-symbols',
        seoTitle:       'Password Generator Without Symbols — Letters & Numbers Only | ToolKit',
        seoH1:          'Password Generator Without Special Characters',
        seoDescription: 'Generate strong passwords without symbols — letters and numbers only. Ideal for systems that reject special characters. Free, browser-based, no signup.',
        intro:          'Some systems still restrict passwords to letters and numbers only — older enterprise software, legacy banking portals, certain IoT device interfaces, and some government systems reject special characters entirely. While symbol-free passwords have lower entropy per character, you can compensate by increasing length. A 20-character alphanumeric password using uppercase and lowercase letters plus digits has approximately 119 bits of entropy — still effectively uncrackable. This generator defaults to 20 characters with uppercase, lowercase, and numbers enabled, and symbols disabled. If the system requires only letters (no numbers either), increase the length further to at least 24 characters to maintain adequate entropy.',
        faq: [
          { q: 'Why do some sites not allow special characters in passwords?', a: 'Usually legacy technical reasons: old databases with character encoding issues, systems that insert passwords into SQL queries without proper parameterization, or input validation written before modern security standards. NIST explicitly recommends that sites accept all printable ASCII characters.' },
          { q: 'How long should a password be without symbols?', a: 'Without symbols, use at least 18-20 characters to maintain strong entropy. With only letters and numbers (62 possible characters), each character contributes about 5.95 bits of entropy. 20 characters gives ~119 bits — still very strong.' },
          { q: 'Is a password without symbols still secure?', a: 'Yes, if it is long enough and truly random. The key word is random — "HelloWorld123" has no symbols but is extremely weak because it follows a predictable pattern. A randomly generated 20-character alphanumeric string is very strong.' },
          { q: 'Can I use only lowercase letters for a password?', a: 'Only if forced to and only with extreme length (30+ characters). Lowercase-only passwords have just 26 possible characters per position (~4.7 bits each), requiring 17+ characters to reach 80 bits of entropy.' },
          { q: 'What if the site also rejects certain letters?', a: 'Some systems reject letters that look like numbers (O, 0, I, l) to avoid confusion. If needed, generate a password and manually replace any ambiguous characters — or increase length to compensate for the reduced character set.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: false },
      },
    ],
  },
  {
    slug:           'word-counter',
    name:           'Word Counter',
    tagline:        'Words, characters, sentences & reading time',
    description:    'Count words, characters, sentences, paragraphs and reading time instantly.',
    seoTitle:       'Free Word Counter Online — Count Words, Characters & Reading Time | ToolKit',
    seoH1:          'Free Word Counter Online',
    seoDescription: 'Count words, characters, sentences, paragraphs and reading time instantly. Includes keyword density and speaking time. Free online tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['word counter', 'word counter online', 'character counter', 'word count tool', 'reading time calculator', 'online word counter free'],
    live:           true,
  },
  {
    slug:           'lorem-ipsum',
    name:           'Lorem Ipsum Generator',
    tagline:        'Placeholder text for mockups & design',
    description:    'Generate Lorem Ipsum placeholder text by words, sentences, or paragraphs.',
    seoTitle:       'Free Lorem Ipsum Generator — Placeholder Text for Mockups | ToolKit',
    seoH1:          'Free Lorem Ipsum Generator Online',
    seoDescription: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences or paragraphs. Classic and random variants. Free online tool for designers and developers.',
    category:       'Text & Writing',
    keywords:       ['lorem ipsum generator', 'lorem ipsum', 'placeholder text generator', 'dummy text generator', 'lorem ipsum online'],
    live:           true,
  },
  {
    slug:           'uuid-generator',
    name:           'UUID Generator',
    tagline:        'Generate v4 UUIDs instantly',
    description:    'Generate cryptographically random UUID v4 identifiers in one click.',
    seoTitle:       'Free UUID Generator Online — Generate v4 UUIDs Instantly | ToolKit',
    seoH1:          'Free UUID Generator Online',
    seoDescription: 'Generate cryptographically random UUID v4 identifiers instantly. Generate 1–50 UUIDs at once, copy all with one click. Free, browser-based, no signup.',
    category:       'Developer Tools',
    keywords:       ['uuid generator', 'uuid generator online', 'unique id generator', 'guid generator', 'random uuid', 'uuid v4 generator'],
    live:           true,
  },
  {
    slug:           'base64',
    name:           'Base64 Encoder / Decoder',
    tagline:        'Encode or decode Base64 strings instantly',
    description:    'Encode text to Base64 or decode Base64 strings back to plain text.',
    seoTitle:       'Free Base64 Encoder & Decoder Online — Encode & Decode Instantly | ToolKit',
    seoH1:          'Free Base64 Encoder & Decoder Online',
    seoDescription: 'Encode text to Base64 or decode Base64 strings back to plain text instantly. Supports UTF-8. Free online Base64 converter — no signup, works in your browser.',
    category:       'Developer Tools',
    keywords:       ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter online', 'encode to base64'],
    live:           true,
  },
  {
    slug:           'json-formatter',
    name:           'JSON Formatter',
    tagline:        'Prettify, minify & validate JSON',
    description:    'Format, beautify, minify and validate JSON data online.',
    seoTitle:       'Free JSON Formatter Online — Prettify, Minify & Validate JSON | ToolKit',
    seoH1:          'Free JSON Formatter & Validator Online',
    seoDescription: 'Format, beautify, minify and validate JSON data instantly. Choose 2 or 4-space indentation. Highlights syntax errors. Free online JSON formatter — no signup.',
    category:       'Developer Tools',
    keywords:       ['json formatter', 'json formatter online', 'json beautifier', 'json validator', 'json prettify', 'format json online', 'json minifier'],
    live:           true,
  },
  {
    slug:           'url-encoder',
    name:           'URL Encoder / Decoder',
    tagline:        'Encode and decode URLs instantly',
    description:    'Encode special characters in URLs or decode percent-encoded strings.',
    seoTitle:       'Free URL Encoder & Decoder Online — Percent Encode / Decode | ToolKit',
    seoH1:          'Free URL Encoder & Decoder Online',
    seoDescription: 'Encode special characters in URLs or decode percent-encoded strings instantly. Swap encode/decode with one click. Free online URL converter — no signup required.',
    category:       'Developer Tools',
    keywords:       ['url encoder', 'url decoder', 'url encode online', 'url decode online', 'percent encoding', 'urlencode', 'url encoding tool'],
    live:           true,
  },
  {
    slug:           'hash-generator',
    name:           'Hash Generator',
    tagline:        'SHA-1, SHA-256, SHA-384, SHA-512 hashes',
    description:    'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text.',
    seoTitle:       'Free Hash Generator Online — SHA-256, SHA-512, SHA-1 | ToolKit',
    seoH1:          'Free Hash Generator Online',
    seoDescription: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text instantly. All hashing runs in your browser via Web Crypto API. Free, no signup, no data stored.',
    category:       'Security',
    keywords:       ['hash generator', 'sha256 generator', 'sha-256 online', 'sha512 generator', 'sha1 hash online', 'text hash generator', 'hash string online'],
    live:           true,
  },
  {
    slug:           'case-converter',
    name:           'Case Converter',
    tagline:        'UPPER, lower, Title, camelCase, snake_case & more',
    description:    'Convert text between uppercase, lowercase, camelCase, snake_case, kebab-case and more.',
    seoTitle:       'Free Case Converter Online — camelCase, snake_case, Title Case & More | ToolKit',
    seoH1:          'Free Case Converter Online',
    seoDescription: 'Convert text to uppercase, lowercase, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE instantly. Free online text case converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['case converter', 'text case converter', 'camelcase converter', 'snake case converter', 'uppercase lowercase converter', 'title case converter', 'convert to camelcase'],
    live:           true,
  },
  {
    slug:           'markdown-editor',
    name:           'Markdown Editor',
    tagline:        'Write and preview Markdown live',
    description:    'Write Markdown with live HTML preview. Copy output as HTML.',
    seoTitle:       'Free Online Markdown Editor — Live Preview & HTML Export | ToolKit',
    seoH1:          'Free Online Markdown Editor with Live Preview',
    seoDescription: 'Write Markdown with instant live preview. Supports headings, bold, italic, code blocks, lists, links and tables. Export as HTML. Free online Markdown editor — no signup.',
    category:       'Text & Writing',
    keywords:       ['markdown editor', 'markdown editor online', 'markdown preview', 'online markdown editor', 'markdown to html', 'live markdown editor'],
    live:           true,
  },
  {
    slug:           'color-palette',
    name:           'Color Palette Generator',
    tagline:        'Generate harmonious color palettes',
    description:    'Generate harmonious color palettes with 7 harmony modes. Copy HEX, RGB, HSL or CSS.',
    seoTitle:       'Free Color Palette Generator — Analogous, Complementary & More | ToolKit',
    seoH1:          'Free Color Palette Generator Online',
    seoDescription: 'Generate beautiful color palettes instantly. Choose analogous, complementary, triadic, tetradic, monochromatic and more. Copy HEX, RGB, HSL or CSS variables. Free, no signup.',
    category:       'Design',
    keywords:       ['color palette generator', 'color palette generator online', 'color scheme generator', 'color picker online', 'complementary color generator', 'color harmony tool'],
    live:           true,
  },
  {
    slug:           'username-generator',
    name:           'Username Generator',
    tagline:        'Creative usernames for social media & gaming',
    description:    'Generate unique usernames for social media, gaming and professional accounts.',
    seoTitle:       'Free Username Generator — Creative Usernames for Social Media & Gaming | ToolKit',
    seoH1:          'Free Username Generator Online',
    seoDescription: 'Generate creative, unique usernames for social media, gaming, Discord, Twitch and more. Choose fun, professional, gamer or minimal styles. Free online username generator.',
    category:       'Design',
    keywords:       ['username generator', 'username generator online', 'random username generator', 'nickname generator', 'gamertag generator', 'discord username generator'],
    live:           true,
  },

  /* ── Coming soon — Security ─────────────────────────── */
  {
    slug:           'bcrypt-generator',
    name:           'Bcrypt Generator',
    tagline:        'Hash and verify passwords with bcrypt',
    description:    'Generate bcrypt hashes from passwords and verify them. Adjustable cost factor.',
    seoTitle:       'Free Bcrypt Generator & Verifier Online | ToolKit',
    seoH1:          'Free Bcrypt Password Hash Generator',
    seoDescription: 'Generate and verify bcrypt password hashes online. Choose cost factor 4–12. Free browser-based bcrypt tool — no data sent to any server.',
    category:       'Security',
    keywords:       ['bcrypt generator', 'bcrypt hash online', 'bcrypt password', 'bcrypt verifier'],
    live:           false,
  },
  {
    slug:           'jwt-decoder',
    name:           'JWT Decoder',
    tagline:        'Decode and inspect JWT tokens',
    description:    'Decode JWT tokens and inspect header, payload and signature. No verification needed.',
    seoTitle:       'Free JWT Decoder Online — Decode & Inspect JSON Web Tokens | ToolKit',
    seoH1:          'Free JWT Decoder Online',
    seoDescription: 'Decode and inspect JWT tokens instantly. View header, payload and signature. Verify expiration. Free online JWT decoder — no data sent to servers.',
    category:       'Security',
    keywords:       ['jwt decoder', 'jwt decoder online', 'decode jwt token', 'json web token decoder', 'jwt inspector'],
    live:           false,
  },
  {
    slug:           'qr-code-generator',
    name:           'QR Code Generator',
    tagline:        'Generate QR codes for URLs and text',
    description:    'Generate QR codes for any URL, text, WiFi, email or phone. Download as PNG or SVG. No watermark, no signup.',
    seoTitle:       'Free QR Code Generator — Create QR Codes Instantly, No Signup | ToolKit',
    seoH1:          'Free QR Code Generator Online',
    seoDescription: 'Generate QR codes for URLs, WiFi, email, phone and more. Download as PNG or SVG. Customize colors and size. 100% free, no watermark, no signup — works in your browser.',
    category:       'Security',
    keywords:       ['qr code generator', 'qr code generator online', 'free qr code generator', 'create qr code', 'qr generator', 'qr code maker', 'qr code creator', 'wifi qr code generator'],
    live:           true,
  },

  /* ── Coming soon — Text & Writing ───────────────────── */
  {
    slug:           'text-diff',
    name:           'Text Diff Checker',
    tagline:        'Compare two texts and highlight differences',
    description:    'Compare two blocks of text and see additions, deletions and changes highlighted.',
    seoTitle:       'Free Text Diff Checker Online — Compare Two Texts | ToolKit',
    seoH1:          'Free Text Diff Checker Online',
    seoDescription: 'Compare two texts and highlight differences instantly. See added, removed and changed lines color-coded. Free online diff tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['text diff checker', 'diff checker online', 'compare two texts', 'text compare online', 'text difference tool'],
    live:           false,
  },
  {
    slug:           'reading-time-calculator',
    name:           'Reading Time Calculator',
    tagline:        'Estimate reading time from word count',
    description:    'Calculate reading and speaking time from any text or word count.',
    seoTitle:       'Free Reading Time Calculator — Estimate Read Time Online | ToolKit',
    seoH1:          'Free Reading Time Calculator Online',
    seoDescription: 'Calculate how long it takes to read any text. Set your reading speed, get reading and speaking time estimates. Free online reading time calculator.',
    category:       'Text & Writing',
    keywords:       ['reading time calculator', 'read time estimator', 'words per minute calculator', 'article reading time'],
    live:           false,
  },
  {
    slug:           'random-text-generator',
    name:           'Random Text Generator',
    tagline:        'Generate random words, sentences and paragraphs',
    description:    'Generate random English words, sentences or paragraphs for testing.',
    seoTitle:       'Free Random Text Generator Online — Words, Sentences & Paragraphs | ToolKit',
    seoH1:          'Free Random Text Generator Online',
    seoDescription: 'Generate random words, sentences or paragraphs instantly. Choose length and style. Great for testing, mockups and development. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['random text generator', 'random word generator', 'random sentence generator', 'random paragraph generator'],
    live:           false,
  },
  {
    slug:           'csv-to-json',
    name:           'CSV to JSON Converter',
    tagline:        'Convert CSV data to JSON format',
    description:    'Paste CSV data and convert it to JSON instantly. Supports headers.',
    seoTitle:       'Free CSV to JSON Converter Online — Convert CSV Instantly | ToolKit',
    seoH1:          'Free CSV to JSON Converter Online',
    seoDescription: 'Convert CSV to JSON format instantly. Paste your CSV data, choose options, and get clean JSON output. Free online CSV to JSON converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['csv to json', 'csv to json converter', 'convert csv to json online', 'csv json converter'],
    live:           false,
  },

  /* ── Coming soon — Developer Tools ─────────────────── */
  {
    slug:           'regex-tester',
    name:           'Regex Tester',
    tagline:        'Test and debug regular expressions live',
    description:    'Test regular expressions with live match highlighting. Supports JavaScript and Python.',
    seoTitle:       'Free Regex Tester Online — Test & Debug Regular Expressions | ToolKit',
    seoH1:          'Free Regex Tester Online',
    seoDescription: 'Test and debug regular expressions with live match highlighting. Supports JavaScript regex flags. See matches, groups and captures instantly. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['regex tester', 'regex tester online', 'regular expression tester', 'regex checker', 'regex debugger online'],
    live:           true,
  },
  {
    slug:           'timestamp-converter',
    name:           'Timestamp Converter',
    tagline:        'Convert Unix timestamps to human-readable dates',
    description:    'Convert Unix timestamps to dates and back. Supports seconds and milliseconds.',
    seoTitle:       'Free Unix Timestamp Converter Online — Epoch to Date | ToolKit',
    seoH1:          'Free Unix Timestamp Converter Online',
    seoDescription: 'Convert Unix/epoch timestamps to human-readable dates and back. Supports seconds and milliseconds. Shows current timestamp live. Free online timestamp converter.',
    category:       'Developer Tools',
    keywords:       ['timestamp converter', 'unix timestamp converter', 'epoch converter', 'epoch to date', 'timestamp to date online'],
    live:           false,
  },
  {
    slug:           'cron-generator',
    name:           'Cron Expression Generator',
    tagline:        'Build and validate cron job schedules',
    description:    'Generate cron expressions visually and see next execution times in plain English.',
    seoTitle:       'Free Cron Expression Generator & Validator Online | ToolKit',
    seoH1:          'Free Cron Expression Generator Online',
    seoDescription: 'Build cron expressions visually, validate syntax and see next 10 run times in plain English. Free cron job generator — no signup, works in browser.',
    category:       'Developer Tools',
    keywords:       ['cron generator', 'cron expression generator', 'cron job generator online', 'crontab generator', 'cron expression validator'],
    live:           false,
  },
  {
    slug:           'css-minifier',
    name:           'CSS Minifier',
    tagline:        'Minify and beautify CSS code',
    description:    'Minify or beautify CSS code. Remove comments, whitespace and optimize output.',
    seoTitle:       'Free CSS Minifier & Beautifier Online — Compress CSS | ToolKit',
    seoH1:          'Free CSS Minifier & Beautifier Online',
    seoDescription: 'Minify CSS to reduce file size or beautify compressed CSS for readability. Removes comments and whitespace. Free online CSS minifier — no signup.',
    category:       'Developer Tools',
    keywords:       ['css minifier', 'css minifier online', 'minify css', 'css compressor', 'css beautifier online'],
    live:           false,
  },
  {
    slug:           'html-entities',
    name:           'HTML Entities Encoder',
    tagline:        'Encode and decode HTML entities',
    description:    'Encode special characters as HTML entities or decode HTML entities back to text.',
    seoTitle:       'Free HTML Entities Encoder & Decoder Online | ToolKit',
    seoH1:          'Free HTML Entities Encoder & Decoder',
    seoDescription: 'Encode special characters as HTML entities or decode HTML entities back to plain text. Free online HTML entity encoder — no signup, instant results.',
    category:       'Developer Tools',
    keywords:       ['html entities encoder', 'html entity decoder', 'html encode online', 'html escape online', 'html entities converter'],
    live:           false,
  },

  /* ── Coming soon — Design ───────────────────────────── */
  {
    slug:           'color-converter',
    name:           'Color Converter',
    tagline:        'Convert between HEX, RGB, HSL, HSV and CMYK',
    description:    'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Live preview, CSS output, one-click copy.',
    seoTitle:       'Free Color Converter — HEX to RGB, HSL, CMYK & More | ToolKit',
    seoH1:          'Free Color Converter Online',
    seoDescription: 'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Get CSS-ready output, live color preview, and one-click copy. Free, browser-based, no signup.',
    category:       'Design',
    keywords:       ['color converter', 'hex to rgb', 'rgb to hex', 'hsl to hex', 'hex to hsl', 'rgb to hsl', 'cmyk to rgb', 'color format converter', 'css color converter'],
    live:           true,
  },
  {
    slug:           'gradient-generator',
    name:           'CSS Gradient Generator',
    tagline:        'Create CSS gradients with live preview',
    description:    'Generate linear and radial CSS gradients visually. Copy the CSS output.',
    seoTitle:       'Free CSS Gradient Generator Online — Linear & Radial Gradients | ToolKit',
    seoH1:          'Free CSS Gradient Generator Online',
    seoDescription: 'Create beautiful linear and radial CSS gradients with live preview. Adjust colors, angle and stops. Copy the CSS output. Free online gradient generator.',
    category:       'Design',
    keywords:       ['css gradient generator', 'gradient generator online', 'linear gradient generator', 'css gradient maker', 'gradient css tool'],
    live:           false,
  },
  {
    slug:           'box-shadow-generator',
    name:           'Box Shadow Generator',
    tagline:        'Create CSS box shadows with live preview',
    description:    'Generate CSS box-shadow values visually with real-time preview.',
    seoTitle:       'Free CSS Box Shadow Generator Online — Live Preview | ToolKit',
    seoH1:          'Free CSS Box Shadow Generator Online',
    seoDescription: 'Create CSS box shadows visually with live preview. Adjust blur, spread, color and inset. Copy the CSS. Free online box shadow generator — no signup.',
    category:       'Design',
    keywords:       ['box shadow generator', 'css box shadow generator', 'box shadow css online', 'css shadow tool'],
    live:           false,
  },
  {
    slug:           'favicon-generator',
    name:           'Favicon Generator',
    tagline:        'Generate favicons from text or emoji',
    description:    'Create favicons from text, emoji or simple icons. Download as ICO and PNG.',
    seoTitle:       'Free Favicon Generator Online — Create Favicons from Text & Emoji | ToolKit',
    seoH1:          'Free Favicon Generator Online',
    seoDescription: 'Generate favicons from text, letters or emoji. Download as ICO (16×16, 32×32) and PNG (192×192). Free online favicon generator — no signup, instant download.',
    category:       'Design',
    keywords:       ['favicon generator', 'favicon generator online', 'create favicon', 'favicon maker', 'free favicon generator'],
    live:           false,
  },
];

/* ── Helpers ──────────────────────────────────────────── */
export const getLiveTools  = () => TOOLS.filter(t => t.live);
export const getSoonTools  = () => TOOLS.filter(t => !t.live);
export const getFeatured   = () => TOOLS.find(t => t.featured);
export const getBySlug     = (slug: string) => TOOLS.find(t => t.slug === slug);
export const getLiveSlugs  = () => getLiveTools().map(t => t.slug);

export const getVariant = (toolSlug: string, variantSlug: string) => {
  const tool = getBySlug(toolSlug);
  return tool?.variants?.find(v => v.slug === variantSlug) ?? null;
};

export const getAllVariantPaths = () => {
  const paths: { params: { slug: string; variant: string } }[] = [];
  for (const tool of getLiveTools()) {
    for (const v of tool.variants ?? []) {
      paths.push({ params: { slug: tool.slug, variant: v.slug } });
    }
  }
  return paths;
};

export const getByCategory = () => {
  const map = new Map<string, ToolMeta[]>();
  for (const tool of TOOLS) {
    if (!map.has(tool.category)) map.set(tool.category, []);
    map.get(tool.category)!.push(tool);
  }
  return map;
};