import type { ToolVariant } from '@/lib/types';

export const variants: ToolVariant[] = [
    /* ── Existing 4 ────────────────────────────────────── */
    {
        slug:           'for-wifi',
        seoTitle:       'WiFi Password Generator — Strong Passwords for Your Router | ToolKit',
        seoH1:          'WiFi Password Generator',
        seoDescription: 'Generate a strong, random WiFi password instantly. WPA2/WPA3 supports up to 63 characters — use all types for maximum security. Free, browser-based, no signup.',
        intro:          'A WiFi password is one of the most important passwords in your home or office — it controls access to your entire network and every device on it. WPA2 and WPA3, the current wireless security standards, support passwords up to 63 characters. Unlike account passwords that need to be typed daily, a WiFi password is entered once per device, which means you can make it as long and random as possible without any usability penalty. This generator defaults to 20 characters with all character types enabled — the recommended setting for a residential or small business router. Avoid common mistakes like using your address, phone number, or a simple word. A strong WiFi password prevents unauthorized access, protects your bandwidth, and stops attackers from using your network as a vector for other attacks.',
        faq: [
            { q: 'How long should a WiFi password be?', a: 'WPA2 and WPA3 support 8–63 characters. Use at least 16 characters for a home network and 20+ for a business network. Longer is always better — you only need to type it once per device.' },
            { q: 'What characters are allowed in a WiFi password?', a: 'WPA2/WPA3 passwords can include uppercase letters, lowercase letters, digits, and most special characters. Avoid characters that may cause issues on some devices: single quotes, double quotes, and backslashes.' },
            { q: 'Do I need to change my WiFi password regularly?', a: 'Only if you suspect a breach — for example, after a guest has used it and you want to revoke access, or after a device has been compromised. Unlike account passwords, WiFi passwords do not need routine rotation.' },
            { q: 'What is the difference between WPA2 and WPA3?', a: 'WPA3 is the newer standard with stronger encryption (SAE instead of PSK) and protection against brute-force attacks. If your router supports WPA3, enable it. If not, WPA2-AES is still considered secure with a strong password.' },
            { q: 'Can my neighbors crack my WiFi password?', a: 'A 16+ character random password with mixed character types would take billions of years to crack with current hardware. The real risk is password reuse or easy-to-guess passwords — not brute force against a strong random one.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-testing',
        seoTitle:       'Password Generator for Testing — Realistic Test Passwords | ToolKit',
        seoH1:          'Password Generator for Testing & Development',
        seoDescription: 'Generate realistic test passwords for development and QA. Configurable length and character sets. Browser-based, no data stored. Free, no signup.',
        intro:          'When building or testing authentication systems, the passwords you use in your test data matter more than most developers realize. Using "password", "test123", or "admin" in test accounts creates two problems: it trains muscle memory for weak passwords, and it risks those credentials leaking into production via database seeds or exported fixtures. A realistic test password — 12-16 characters with mixed types — also validates that your input fields, password strength meters, and hashing functions handle real-world values correctly. Truncation bugs, encoding issues with special characters, and bcrypt length limits (72 bytes) are all easier to catch with realistic passwords. This generator lets you configure exactly the character set and length you need for your test scenarios, from simple alphanumeric passwords to full-complexity strings that stress-test your validation logic.',
        faq: [
            { q: 'What password length should I use for test data?', a: 'Match what real users will create — 12-20 characters covers the realistic range. Also test edge cases: the minimum allowed length (usually 8), the maximum (often 64 or 128), and lengths that would exceed bcrypt\'s 72-byte limit.' },
            { q: 'Should test passwords include special characters?', a: 'Yes — special characters expose encoding bugs, escaping issues in SQL/HTML, and validation logic errors. Test with characters like !@#$%^&* and also with edge cases like quotes and backslashes.' },
            { q: 'Can I use the same test password across environments?', a: 'Use different passwords for development, staging, and production test accounts. Never seed a production database with the same credentials used in development.' },
            { q: 'What is bcrypt\'s 72-byte password limit?', a: 'bcrypt truncates input at 72 bytes. This means passwords longer than ~72 ASCII characters are silently treated as identical after that point. If your app uses bcrypt, test this boundary explicitly.' },
            { q: 'How do I generate bulk test passwords?', a: 'Click the generator multiple times, or use the copy button for each. For programmatic bulk generation, use crypto.randomUUID() for simple tokens or the Web Crypto API\'s getRandomValues() for full password generation in Node.js or the browser.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'strong-20-characters',
        seoTitle:       'Strong 20 Character Password Generator — High-Security Passwords | ToolKit',
        seoH1:          '20 Character Password Generator',
        seoDescription: 'Generate strong 20-character passwords instantly. 20 characters with mixed types gives ~131 bits of entropy — effectively uncrackable. Free, browser-based, no signup.',
        intro:          'A 20-character random password with uppercase letters, lowercase letters, numbers, and symbols provides approximately 131 bits of entropy. To put that in perspective: even if every computer on Earth attempted a trillion guesses per second, cracking it would take longer than the current age of the universe. The NIST Digital Identity Guidelines recommend at least 15 characters for general accounts — 20 characters gives you a significant safety margin above that threshold. Twenty characters is also the sweet spot between security and usability: long enough to be essentially uncrackable, short enough to copy-paste or type without excessive effort. This generator defaults to exactly 20 characters with all four character sets enabled, producing the highest-entropy output this length allows.',
        faq: [
            { q: 'How secure is a 20-character password?', a: 'A 20-character password using all character types has approximately 131 bits of entropy. At 10 billion guesses per second (a high-end GPU attack), cracking it would take around 10²⁰ years — effectively impossible with any foreseeable technology.' },
            { q: 'Is 20 characters enough for all accounts?', a: 'Yes — 20 characters exceeds the NIST recommendation of 15 characters and is sufficient for any current use case including banking, email, and cloud storage. For extremely sensitive accounts, you can go up to 32 or 64 characters.' },
            { q: 'Do all websites accept 20-character passwords?', a: 'Most modern websites accept passwords up to 64 characters (NIST recommendation for maximum length). Some older systems have lower limits — typically 32 or 20 characters. If a site rejects your password, try reducing to 16 characters first.' },
            { q: 'What is the entropy of a 20-character password?', a: 'With 95 printable ASCII characters available (uppercase, lowercase, digits, symbols), each character contributes log₂(95) ≈ 6.57 bits of entropy. 20 characters × 6.57 = ~131 bits total.' },
            { q: 'Should I use 20 characters or a passphrase?', a: 'A 20-character random password is stronger per character but impossible to memorize. Use it for any password stored in a manager. Use a passphrase only for the few passwords you must type manually — like your password manager master password.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'no-symbols',
        seoTitle:       'Password Generator Without Symbols — Letters & Numbers Only | ToolKit',
        seoH1:          'Password Generator Without Special Characters',
        seoDescription: 'Generate strong passwords without symbols — letters and numbers only. Ideal for systems that reject special characters. Free, browser-based, no signup.',
        intro:          'Some systems still restrict passwords to letters and numbers only — older enterprise software, legacy banking portals, certain IoT device interfaces, and some government systems reject special characters entirely. While symbol-free passwords have lower entropy per character, you can compensate by increasing length. A 20-character alphanumeric password using uppercase and lowercase letters plus digits has approximately 119 bits of entropy — still effectively uncrackable. This generator defaults to 20 characters with uppercase, lowercase, and numbers enabled, and symbols disabled. If the system requires only letters (no numbers either), increase the length further to at least 24 characters to maintain adequate entropy.',
        faq: [
            { q: 'Why do some sites not allow special characters in passwords?', a: 'Usually legacy technical reasons: old databases with character encoding issues, systems that insert passwords into SQL queries without proper parameterization, or input validation written before modern security standards. NIST explicitly recommends that sites accept all printable ASCII characters.' },
            { q: 'How long should a password be without symbols?', a: 'Without symbols, use at least 18-20 characters to maintain strong entropy. With only letters and numbers (62 possible characters), each character contributes about 5.95 bits of entropy. 20 characters gives ~119 bits — still very strong.' },
            { q: 'Is a password without symbols still secure?', a: 'Yes, if it is long enough and truly random. The key word is random — "HelloWorld123" has no symbols but is extremely weak because it follows a predictable pattern. A randomly generated 20-character alphanumeric string is very strong.' },
            { q: 'Can I use only lowercase letters for a password?', a: 'Only if forced to and only with extreme length (30+ characters). Lowercase-only passwords have just 26 possible characters per position (~4.7 bits each), requiring 17+ characters to reach 80 bits of entropy.' },
            { q: 'What if the site also rejects certain letters?', a: 'Some systems reject letters that look like numbers (O, 0, I, l) to avoid confusion. If needed, generate a password and manually replace any ambiguous characters — or increase length to compensate for the reduced character set.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },

    /* ── By length / strength ──────────────────────────── */
    {
        slug:           '8-characters',
        seoTitle:       '8 Character Password Generator — Minimum Length Passwords | ToolKit',
        seoH1:          '8 Character Password Generator',
        seoDescription: 'Generate random 8-character passwords instantly. Meet minimum length requirements for most websites. All character types enabled. Free, browser-based, no signup.',
        intro:          'Eight characters is the minimum password length accepted by most websites and services today. While security experts recommend longer passwords, there are situations where 8 characters is all a system allows — older enterprise portals, legacy banking systems, and some embedded device interfaces enforce this exact limit. An 8-character password using all four character types (uppercase, lowercase, digits, symbols) provides approximately 52 bits of entropy. That is not ideal for high-security accounts, but it is far stronger than common 8-character passwords like "Password1!" which follow predictable patterns. If you are forced to use 8 characters, make every character count by enabling all character types and generating it randomly rather than choosing it yourself. For any system that allows longer passwords, use at least 16 characters instead.',
        faq: [
            { q: 'Is an 8-character password secure enough?', a: 'For high-value accounts like banking or email, 8 characters is the bare minimum and not recommended. For low-risk accounts where the system enforces a maximum of 8 characters, a random 8-character password with all character types is acceptable. Always use longer passwords when possible.' },
            { q: 'How long would it take to crack an 8-character password?', a: 'A random 8-character password with all character types (~52 bits of entropy) could be cracked in hours to days by a determined attacker with GPU hardware. An 8-character password using only lowercase letters could be cracked in seconds.' },
            { q: 'Why do some sites limit passwords to 8 characters?', a: 'Legacy systems built decades ago sometimes store passwords in fixed-width database fields or use older hashing algorithms with length restrictions. NIST now recommends supporting at least 64 characters, but many older systems have not been updated.' },
            { q: 'How can I make an 8-character password as strong as possible?', a: 'Use all four character types (uppercase, lowercase, numbers, symbols) and generate it randomly. Never use dictionary words, names, dates, or predictable patterns like "Abcdef1!".' },
        ],
        defaults: { length: 8, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           '12-characters',
        seoTitle:       '12 Character Password Generator — Balanced Security Passwords | ToolKit',
        seoH1:          '12 Character Password Generator',
        seoDescription: 'Generate strong 12-character passwords instantly. 12 characters with mixed types gives ~79 bits of entropy — solid security for everyday accounts. Free, browser-based.',
        intro:          'Twelve characters is widely considered the practical minimum for a strong password in 2025. At this length with all four character types enabled, you get approximately 79 bits of entropy — enough to resist brute-force attacks from even high-end GPU clusters for decades. Many security guidelines, including those from Microsoft and Google, recommend 12 characters as the starting point for personal accounts. It strikes the right balance: short enough to type on a phone keyboard when needed, long enough to provide meaningful security. This generator defaults to 12 characters with uppercase, lowercase, numbers, and symbols all enabled. For accounts that store sensitive data — banking, primary email, cloud storage — consider stepping up to 16 or 20 characters for additional margin.',
        faq: [
            { q: 'Is 12 characters enough for a strong password?', a: 'Yes, for most personal accounts. A random 12-character password with all character types has ~79 bits of entropy. This would take centuries to crack with current GPU technology. For high-security accounts, 16-20 characters is better.' },
            { q: 'How does 12 characters compare to 8 characters?', a: 'Dramatically stronger. Each additional character multiplies the number of possible combinations by ~95 (the number of printable ASCII characters). 12 characters is roughly 81 million times harder to crack than 8 characters.' },
            { q: 'Should I use 12 or 16 characters?', a: 'If the password will be stored in a password manager (copy-paste), use 16 or 20. If you need to type it manually sometimes, 12 characters with all types is a solid choice that balances security and usability.' },
            { q: 'What accounts should use at least 12 characters?', a: 'All accounts should use at least 12 characters. Prioritize maximum length for email, banking, cloud storage, and any account that could be used to reset other passwords.' },
        ],
        defaults: { length: 12, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           '32-characters',
        seoTitle:       '32 Character Password Generator — Maximum Security Passwords | ToolKit',
        seoH1:          '32 Character Password Generator',
        seoDescription: 'Generate ultra-strong 32-character passwords with ~210 bits of entropy. Ideal for API keys, master passwords, and encryption keys. Free, browser-based, no signup.',
        intro:          'A 32-character random password with all character types provides approximately 210 bits of entropy — far beyond what any brute-force attack could crack, even with theoretical future quantum computers using Grover\'s algorithm (which would halve the effective entropy to ~105 bits, still uncrackable). This length is ideal for API keys, service account passwords, database connection strings, encryption key passphrases, and any credential that will never be typed manually. At 32 characters, the password is always stored in a password manager or configuration file, so usability is not a concern. Many security-conscious organizations mandate 32-character passwords for infrastructure credentials. This generator defaults to 32 characters with all types enabled, producing maximum-entropy output suitable for the most sensitive applications.',
        faq: [
            { q: 'When should I use a 32-character password?', a: 'Use 32 characters for API keys, database passwords, service accounts, encryption passphrases, and any credential stored in a password manager or config file. There is no usability penalty since you never type it manually.' },
            { q: 'Is 32 characters overkill for a regular account?', a: 'Not really — if you use a password manager, there is no downside to 32 characters. However, 16-20 characters is already effectively uncrackable for regular accounts. The extra length matters more for infrastructure and encryption credentials.' },
            { q: 'Do all systems accept 32-character passwords?', a: 'Most modern systems accept up to 64-128 characters. Some legacy systems may truncate at 16 or 20 characters without warning. Test by verifying you can log in with the full password after setting it.' },
            { q: 'How does 32 characters compare to a 256-bit key?', a: 'A 32-character password with all ASCII types has ~210 bits of entropy, which is comparable to a 210-bit cryptographic key. A true 256-bit key would require ~39 random characters from the full printable ASCII set.' },
        ],
        defaults: { length: 32, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           '64-characters',
        seoTitle:       '64 Character Password Generator — Ultra-Secure Long Passwords | ToolKit',
        seoH1:          '64 Character Password Generator',
        seoDescription: 'Generate ultra-secure 64-character passwords with ~420 bits of entropy. Maximum length for encryption keys and infrastructure credentials. Free, browser-based.',
        intro:          'Sixty-four characters is the maximum password length recommended by NIST SP 800-63B, and it represents the upper practical limit for most authentication systems. A 64-character random password with all character types delivers approximately 420 bits of entropy — a number so large that expressing the time to crack it requires scientific notation with triple-digit exponents. This length is used for the most sensitive infrastructure: root database passwords, HSM (Hardware Security Module) passphrases, master encryption keys, and air-gapped system credentials. At this length, even theoretical attacks using quantum computing with Grover\'s algorithm would still face ~210 bits of effective entropy. This generator produces 64-character strings using the full printable ASCII character set. Always store these in a secure vault — they are never meant to be memorized or typed.',
        faq: [
            { q: 'Why would I need a 64-character password?', a: 'For maximum-security credentials: root database passwords, encryption key passphrases, HSM access codes, and infrastructure credentials that must withstand any foreseeable attack, including quantum computing.' },
            { q: 'Can any system handle a 64-character password?', a: 'NIST recommends systems accept at least 64 characters. Most modern platforms do. Some older systems may silently truncate — always verify by logging in with the full password immediately after setting it.' },
            { q: 'Is 64 characters quantum-resistant?', a: 'Yes. Grover\'s algorithm halves the effective bit strength, reducing ~420 bits to ~210 bits. Even 210 bits is far beyond any foreseeable computational capability.' },
            { q: 'Should I use 64 characters for my email password?', a: 'You can, but 20-32 characters is more than sufficient for personal accounts. 64 characters is primarily for infrastructure and encryption use cases where the password is always copy-pasted from a vault.' },
        ],
        defaults: { length: 64, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },

    /* ── By character type ─────────────────────────────── */
    {
        slug:           'numbers-only',
        seoTitle:       'Number-Only Password Generator — Numeric PINs & Passcodes | ToolKit',
        seoH1:          'Number-Only Password Generator',
        seoDescription: 'Generate random numeric passwords and PINs. Digits only (0-9). Ideal for phone PINs, lock screens, and systems requiring numeric-only codes. Free, browser-based.',
        intro:          'Some systems require numeric-only passwords: phone lock screens, SIM PINs, safe combinations, building access codes, and legacy banking systems that only accept digits. A purely numeric password has significantly lower entropy per character than a mixed-type password — each digit provides only ~3.32 bits (log₂(10)) compared to ~6.57 bits for the full printable ASCII set. To compensate, increase the length: a 10-digit random PIN has about 33 bits of entropy (sufficient for a phone lock screen with rate limiting), while a 20-digit numeric password reaches ~66 bits (adequate for most systems). This generator outputs random digits with configurable length. For any system that accepts mixed characters, always prefer a shorter mixed-type password over a longer numeric-only one.',
        faq: [
            { q: 'How long should a numeric-only password be?', a: 'It depends on the use case. Phone PINs: 6-8 digits (with rate limiting). Banking PINs: 4-6 digits (card required as second factor). Numeric passwords for websites: at least 16-20 digits to compensate for the small character set.' },
            { q: 'Is a numeric password secure?', a: 'Only with sufficient length and rate limiting. A 4-digit PIN has only 10,000 combinations — it relies on the system locking after failed attempts. A 20-digit random number has ~66 bits of entropy, which is decent but weaker than a 12-character mixed-type password.' },
            { q: 'Why do some systems only accept numbers?', a: 'Physical keypads (ATMs, door locks, safes) often have only digit buttons. Phone lock screens prioritize fast input with a numeric keypad. Some legacy systems were designed before modern password standards.' },
            { q: 'What is the difference between a PIN and a numeric password?', a: 'A PIN (Personal Identification Number) is typically 4-8 digits and used with a physical token (card, phone). A numeric password can be any length and is used alone for authentication. PINs rely on rate limiting for security; numeric passwords rely on length.' },
        ],
        defaults: { length: 16, uppercase: false, lowercase: false, numbers: true, symbols: false },
    },
    {
        slug:           'letters-only',
        seoTitle:       'Letters-Only Password Generator — Alphabetic Passwords | ToolKit',
        seoH1:          'Letters-Only Password Generator',
        seoDescription: 'Generate random passwords using only letters (A-Z, a-z). No digits, no symbols. For systems requiring alphabetic-only input. Free, browser-based, no signup.',
        intro:          'Certain systems restrict passwords to letters only — no digits, no symbols. This is common in older mainframe environments, some educational platforms, and systems where the password must be spoken aloud (phone support verification codes, for example). With 52 possible characters (26 uppercase + 26 lowercase), each character contributes ~5.7 bits of entropy. A 16-character letters-only password provides ~91 bits of entropy — strong enough for most purposes. For maximum security within this constraint, always use both uppercase and lowercase letters and generate randomly rather than choosing words. This generator defaults to 16 characters with both cases enabled and all other character types disabled.',
        faq: [
            { q: 'How long should a letters-only password be?', a: 'At least 16 characters to reach ~91 bits of entropy. If only one case is allowed (e.g., uppercase only), increase to 20+ characters to compensate for the reduced character set (26 vs 52 characters).' },
            { q: 'Is a letters-only password weaker than a mixed one?', a: 'Per character, yes — 5.7 bits vs 6.57 bits. But a 16-character letters-only password (~91 bits) is still stronger than a 12-character mixed password (~79 bits). Length compensates for character set limitations.' },
            { q: 'Why would a system restrict to letters only?', a: 'Phone verification codes meant to be spoken aloud, legacy mainframe systems, some educational platforms, and systems where special characters cause encoding issues in the underlying database.' },
            { q: 'Should I use uppercase and lowercase?', a: 'Always, if the system allows it. Using both cases doubles the character set from 26 to 52, adding ~1 bit of entropy per character. That is a significant improvement over the same length with one case.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: false, symbols: false },
    },
    {
        slug:           'alphanumeric',
        seoTitle:       'Alphanumeric Password Generator — Letters & Numbers Only | ToolKit',
        seoH1:          'Alphanumeric Password Generator',
        seoDescription: 'Generate random alphanumeric passwords (A-Z, a-z, 0-9). No special characters. Compatible with all systems. Free, browser-based, no signup.',
        intro:          'Alphanumeric passwords — letters and numbers only, no symbols — are the most universally compatible password format. Every system, device, and platform accepts them without issues. With 62 possible characters (26 uppercase + 26 lowercase + 10 digits), each character contributes ~5.95 bits of entropy. A 16-character alphanumeric password provides ~95 bits — strong enough for virtually any use case. This format avoids the common frustrations of symbol-containing passwords: copying issues in terminals, escaping problems in shell scripts, encoding errors in URLs, and rejection by systems with restrictive character policies. If you use a password manager and never type passwords manually, symbols add marginal value. Many security professionals use alphanumeric passwords with increased length as their default choice.',
        faq: [
            { q: 'Is alphanumeric as secure as passwords with symbols?', a: 'Nearly. Each alphanumeric character gives ~5.95 bits vs ~6.57 bits with symbols. A 16-character alphanumeric password (~95 bits) is comparable to a 14-character mixed password (~92 bits). Add 2-3 characters to match the entropy of a shorter symbol-containing password.' },
            { q: 'Why choose alphanumeric over full complexity?', a: 'Universal compatibility — no system rejects alphanumeric passwords. No escaping issues in scripts, config files, or URLs. Easy to type on any keyboard layout. The minor entropy loss per character is easily offset by adding 1-2 extra characters.' },
            { q: 'What systems have trouble with special characters?', a: 'Shell scripts (characters like $ and ! have special meaning), older databases, URL parameters (& and = conflict), XML/HTML (< and > cause parsing issues), and some IoT devices with limited keyboard input.' },
            { q: 'How long should an alphanumeric password be?', a: 'At least 16 characters for personal accounts, 20+ for sensitive accounts, 32+ for infrastructure credentials. The goal is to match or exceed 80 bits of entropy for personal use and 128+ bits for infrastructure.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'hex',
        seoTitle:       'Hex Password Generator — Hexadecimal Keys & Tokens | ToolKit',
        seoH1:          'Hex Password Generator',
        seoDescription: 'Generate random hexadecimal strings (0-9, a-f). Ideal for encryption keys, tokens, and API secrets. Configurable length. Free, browser-based, no signup.',
        intro:          'Hexadecimal strings — characters 0-9 and a-f — are the standard format for encryption keys, authentication tokens, MAC addresses, and many API secrets. Each hex character represents exactly 4 bits, making it easy to calculate key strength: a 32-character hex string is a 128-bit key, 64 characters is 256 bits. This generator produces random hex strings using a cryptographically secure random number generator (Web Crypto API). Common use cases include WEP/WPA keys, AES encryption keys, HMAC secrets, session tokens, and color codes. Note that hex passwords have lower entropy per character (~4 bits) than full alphanumeric passwords (~5.95 bits), so they need to be longer to achieve the same strength. A 32-hex-character password (128 bits) is equivalent in strength to about a 22-character alphanumeric password.',
        faq: [
            { q: 'What is a hexadecimal password used for?', a: 'Encryption keys (AES-128, AES-256), authentication tokens, HMAC secrets, WEP/WPA network keys, API secrets, session identifiers, and any system that requires input in hex format.' },
            { q: 'How long should a hex password be?', a: 'It depends on the required bit strength: 32 hex characters = 128 bits (standard encryption), 48 hex characters = 192 bits, 64 hex characters = 256 bits (maximum standard encryption strength).' },
            { q: 'Is hex the same as Base16?', a: 'Yes. Hexadecimal (hex) is Base16 encoding, using digits 0-9 and letters a-f (or A-F). Each character represents 4 bits of data, making it a convenient way to represent binary data in text form.' },
            { q: 'Should I use uppercase or lowercase hex?', a: 'Both are valid and represent the same values. Lowercase (a-f) is more common in modern programming (JavaScript, Python, CSS color codes). Uppercase (A-F) is traditional in networking and hardware contexts.' },
        ],
        defaults: { length: 32, uppercase: false, lowercase: true, numbers: true, symbols: false },
    },

    /* ── By platform / service ─────────────────────────── */
    {
        slug:           'for-bank',
        seoTitle:       'Bank Password Generator — Secure Banking Passwords | ToolKit',
        seoH1:          'Bank Account Password Generator',
        seoDescription: 'Generate strong passwords specifically for banking and financial accounts. Meets common bank requirements. Free, browser-based, nothing stored.',
        intro:          'Banking passwords protect your financial life — they deserve maximum attention. Most banks require 8-20 characters with at least one uppercase letter, one lowercase letter, one number, and one symbol, though many older banking platforms restrict allowed characters more than modern services. The biggest risk to bank accounts is not brute-force attacks (banks have rate limiting and account lockouts) but credential stuffing — attackers using email/password combinations leaked from other sites. This means your bank password must be unique and never reused anywhere else. This generator defaults to 16 characters with all types enabled, meeting the requirements of virtually every bank while providing far more security than the typical minimum. Always enable two-factor authentication on banking accounts as an additional layer — a strong password alone is necessary but not sufficient for financial security.',
        faq: [
            { q: 'How long should my bank password be?', a: 'At least 16 characters. Most banks accept 8-20+ characters. Use the maximum length the bank allows. A 16-character random password with all types provides ~105 bits of entropy — far beyond what any attacker could crack.' },
            { q: 'Why do banks restrict special characters?', a: 'Legacy banking software often runs on older systems (COBOL mainframes, AS/400) with limited character set support. Some banks also restrict characters that could cause SQL injection if their input handling is improperly coded.' },
            { q: 'Should I change my bank password regularly?', a: 'NIST no longer recommends routine password rotation. Change your bank password only if you suspect it has been compromised, if the bank reports a data breach, or if you have shared it with someone who no longer needs access.' },
            { q: 'Is my bank password the most important one?', a: 'Your email password is arguably more important — an attacker who controls your email can reset any password, including your bank. Prioritize both your email and bank passwords, and use unique passwords for each.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-email',
        seoTitle:       'Email Password Generator — Secure Your Gmail & Outlook | ToolKit',
        seoH1:          'Email Account Password Generator',
        seoDescription: 'Generate strong passwords for email accounts — Gmail, Outlook, Yahoo and more. Your email is the master key to all other accounts. Free, browser-based.',
        intro:          'Your email password is arguably the most important password you have. Email is the recovery method for nearly every other account — banking, social media, cloud storage, work tools. An attacker who gains access to your email can reset passwords across your entire digital life within minutes. Gmail, Outlook, Yahoo, and other major providers all support long passwords with full character sets. This generator defaults to 20 characters with all types enabled, providing approximately 131 bits of entropy. Since you typically log into email infrequently on new devices (most stay logged in), there is no reason to compromise on length. Always pair your email password with two-factor authentication (preferably a hardware key or authenticator app, not SMS). Never reuse your email password on any other service.',
        faq: [
            { q: 'Why is my email password the most important?', a: 'Because email is the password reset mechanism for almost every other account. An attacker with access to your email can reset your bank, social media, and cloud storage passwords. Securing email secures everything downstream.' },
            { q: 'How long should my email password be?', a: 'At least 16-20 characters. Gmail and Outlook both support very long passwords. Since you rarely type it (autofill or stay logged in), there is no reason to use fewer than 20 characters.' },
            { q: 'Should I use the same password for all email accounts?', a: 'Never. Each email account should have a unique password. If one is compromised, the others remain secure. Use a password manager to handle multiple unique passwords.' },
            { q: 'Is two-factor authentication enough without a strong password?', a: 'No. Two-factor authentication adds a layer but is not foolproof — SIM swapping can bypass SMS codes, and phishing can capture authenticator codes in real time. A strong unique password is the essential foundation.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-gaming',
        seoTitle:       'Gaming Password Generator — Secure Steam, Xbox & PSN Accounts | ToolKit',
        seoH1:          'Gaming Account Password Generator',
        seoDescription: 'Generate strong passwords for Steam, Xbox, PlayStation, Epic Games, and Discord. Protect your game library and in-game purchases. Free, browser-based.',
        intro:          'Gaming accounts represent real financial value — Steam libraries worth hundreds or thousands of dollars, in-game purchases, rare items, and linked payment methods make them high-value targets for attackers. Account theft is rampant in gaming: phishing through fake trade offers, credential stuffing from other breaches, and social engineering through Discord are the most common attack vectors. Steam, Xbox Live, PlayStation Network, Epic Games Store, and Battle.net all support strong passwords with mixed character types. This generator defaults to 16 characters with all types enabled. Beyond password strength, enable Steam Guard, Xbox two-step verification, or PlayStation two-step verification on every gaming platform. Never enter your password on sites reached through links in chat messages — always navigate to the platform directly.',
        faq: [
            { q: 'Why are gaming accounts targeted?', a: 'Steam libraries can be worth thousands of dollars. CS2 and TF2 items have real monetary value. Stolen accounts are sold on black markets or used to launder money through in-game transactions.' },
            { q: 'What password length should I use for Steam?', a: 'Steam accepts passwords up to 64 characters. Use at least 16 characters with all character types. Since you rarely type it (Steam remembers your login), there is no reason to use a short password.' },
            { q: 'Is Discord a gaming platform for password purposes?', a: 'Yes — Discord accounts are frequently targeted because they are linked to game servers, communities, and sometimes Nitro subscriptions. Use a unique, strong password for Discord and enable two-factor authentication.' },
            { q: 'How do gaming account breaches happen?', a: 'The most common methods are: phishing (fake login pages linked from chat), credential stuffing (reused passwords from other breaches), malware (keyloggers from pirated game downloads), and social engineering (fake Steam support messages).' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-social-media',
        seoTitle:       'Social Media Password Generator — Secure Instagram, TikTok & More | ToolKit',
        seoH1:          'Social Media Password Generator',
        seoDescription: 'Generate strong passwords for Instagram, TikTok, Facebook, Twitter/X and more. Protect your accounts from hacking. Free, browser-based, no signup.',
        intro:          'Social media accounts are among the most commonly hacked accounts on the internet. Instagram, TikTok, Facebook, Twitter/X, and LinkedIn accounts are targeted for identity theft, spam distribution, cryptocurrency scams, and impersonation. The damage goes beyond the account itself — a compromised social media profile can be used to scam your followers, damage your reputation, or access other services connected via social login ("Sign in with Google/Facebook"). Most social platforms support passwords up to 128 characters with full character sets. This generator defaults to 16 characters with all types enabled. Use a unique password for each platform — if your Instagram password leaks, your TikTok should remain secure. Enable two-factor authentication on every social media account, preferably using an authenticator app rather than SMS.',
        faq: [
            { q: 'Why are social media accounts frequently hacked?', a: 'Weak and reused passwords are the primary cause. Many users use the same simple password across Instagram, TikTok, and email. When any one service is breached, attackers try those credentials everywhere. Additionally, phishing DMs and fake login pages are extremely common on social platforms.' },
            { q: 'What password length do social media platforms support?', a: 'Most support long passwords: Instagram up to 128 characters, Facebook up to 128, Twitter/X up to 128, TikTok up to 20, LinkedIn up to 400. Use at least 16 characters on every platform.' },
            { q: 'Should I use different passwords for each social media account?', a: 'Absolutely. A unique password for each account ensures that a breach on one platform does not compromise your other accounts. Use a password manager to track them all.' },
            { q: 'Can someone hack my account even with a strong password?', a: 'Yes — through phishing, SIM swapping (for SMS-based 2FA), or session hijacking. A strong password prevents brute-force and credential stuffing attacks, but you also need two-factor authentication and awareness of phishing attempts.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-school',
        seoTitle:       'School Password Generator — Student & Campus Account Passwords | ToolKit',
        seoH1:          'School & Student Password Generator',
        seoDescription: 'Generate secure passwords for school and university accounts. Meets typical campus IT requirements. Easy to type. Free, browser-based, no signup.',
        intro:          'School and university accounts often have specific password policies: minimum 8-12 characters, at least one uppercase letter, one number, and sometimes one symbol. Many students reuse their school password across personal accounts — this is dangerous because educational institutions are frequent targets for cyberattacks, and a breach of your university credentials could expose every account sharing that password. Campus accounts also typically connect to email, cloud storage (OneDrive, Google Drive), library systems, and sometimes financial aid portals. This generator defaults to 14 characters with all types enabled — long enough to be secure, meeting all common campus IT requirements, and practical enough to type on a shared lab computer. Always use a unique password for your school account and store it in a password manager.',
        faq: [
            { q: 'Why do school IT departments have specific password rules?', a: 'Educational institutions must comply with data protection regulations (FERPA in the US, GDPR in Europe) and protect systems shared by thousands of users. Specific rules ensure a baseline security level across all student and staff accounts.' },
            { q: 'Is my school account a high-value target?', a: 'Yes — school accounts access email, cloud storage, academic records, and sometimes financial aid. Universities are heavily targeted by phishing campaigns because students are less security-aware than corporate employees and the accounts connect to valuable data.' },
            { q: 'Can I use the same password for school and personal accounts?', a: 'Never. School systems are shared environments with higher breach risk. If your school credentials are compromised, every account sharing that password is also compromised. Use unique passwords everywhere.' },
            { q: 'What if I need to type the password on a shared computer?', a: 'Use 14-16 characters — long enough to be secure but practical to type. Avoid extreme lengths like 32+ characters for accounts you type manually on lab or library computers. Always log out completely when finished.' },
        ],
        defaults: { length: 14, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },

    /* ── By purpose ────────────────────────────────────── */
    {
        slug:           'bulk',
        seoTitle:       'Bulk Password Generator — Generate Multiple Passwords at Once | ToolKit',
        seoH1:          'Bulk Password Generator',
        seoDescription: 'Generate multiple random passwords at once. Create 10, 50, or 100 secure passwords in one click. Ideal for teams and provisioning. Free, browser-based.',
        intro:          'When provisioning user accounts, setting up test environments, or rotating credentials across multiple services, you need many unique passwords at once. Generating them one at a time is tedious and error-prone — copying the wrong password to the wrong account is a common operational mistake. This bulk generator creates multiple cryptographically random passwords simultaneously, each with the same security properties as a single generated password. Common use cases include IT teams onboarding new employees, DevOps engineers rotating database credentials, QA teams creating test accounts, and anyone migrating to a password manager who needs to replace reused passwords across many services. Each password is generated independently using the Web Crypto API, ensuring no correlation between outputs.',
        faq: [
            { q: 'How many passwords can I generate at once?', a: 'You can generate as many as you need by clicking the generate button repeatedly. Each click produces a fresh, cryptographically random password that is completely independent of the previous ones.' },
            { q: 'Are bulk-generated passwords as secure as single ones?', a: 'Yes. Each password is generated independently using the same cryptographically secure random number generator (Web Crypto API). Generating multiple passwords does not reduce the randomness or security of any individual password.' },
            { q: 'What is the best way to distribute bulk passwords?', a: 'Never send passwords in plain text via email. Use a password manager with sharing features (1Password, Bitwarden), a secure messaging platform with disappearing messages, or an in-person handoff for the most sensitive credentials.' },
            { q: 'Should all bulk passwords have the same settings?', a: 'For uniform environments (all users on the same system), yes — use consistent length and character requirements. For different systems with different requirements, generate separate batches with appropriate settings for each system.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'memorable',
        seoTitle:       'Memorable Password Generator — Easy to Remember, Hard to Crack | ToolKit',
        seoH1:          'Memorable Password Generator',
        seoDescription: 'Generate passwords that are easy to remember but hard to crack. Uses pronounceable patterns with mixed characters. Free, browser-based, no signup.',
        intro:          'There are a few passwords you need to actually memorize: your password manager master password, your computer login, and perhaps your phone PIN. For these, a purely random string like "xK#9mQ$2pL" is impractical — you will forget it, write it on a sticky note, or reset it constantly. A memorable password takes a different approach: it uses patterns that human memory can latch onto while maintaining enough randomness to resist attacks. The best strategy is a passphrase — four to six random words combined with numbers and symbols, like "correct-horse-battery-staple" but with added complexity. This generator creates passwords that balance memorability with security. For any password that goes into a password manager (not memorized), always prefer a fully random password instead.',
        faq: [
            { q: 'When should I use a memorable password vs a random one?', a: 'Memorable passwords are only for the few passwords you must type from memory: password manager master password, computer login, phone unlock. Every other password should be fully random and stored in a password manager.' },
            { q: 'How secure is a memorable password?', a: 'It depends on the method. A 4-word passphrase from a 7,776-word list provides ~51 bits of entropy. A 6-word passphrase provides ~77 bits. Adding numbers and symbols between words increases entropy further. This is weaker per character than a random string but strong enough for passwords protected by rate limiting.' },
            { q: 'What makes a password memorable?', a: 'Patterns, rhythm, and visual imagery. "Purple-Tiger-Runs-42!" is far more memorable than "pTr42!" because your brain can form a mental image. Length from natural words compensates for the lower entropy per character.' },
            { q: 'Is "correct horse battery staple" still a good password?', a: 'The concept is sound but that specific phrase is now in every dictionary attack list. Always generate your own random word combinations. Add numbers and symbols between words for additional entropy.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'passphrase',
        seoTitle:       'Passphrase Generator — Random Word Passwords for Master Keys | ToolKit',
        seoH1:          'Passphrase Generator',
        seoDescription: 'Generate secure passphrases from random words. Ideal for master passwords and encryption keys you need to memorize. Free, browser-based, no signup.',
        intro:          'A passphrase is a password made of multiple random words — like "marble-sunset-notebook-river" — instead of a string of random characters. The concept was popularized by the XKCD comic "correct horse battery staple" and formalized by the Diceware method. Passphrases solve a specific problem: they provide high entropy while remaining memorable enough to type without a password manager. A four-word passphrase from a large word list provides roughly 50-60 bits of entropy; six words provides 75-90 bits. The trade-off is length — passphrases are typically 20-40 characters long but far easier to remember than a 16-character random string. Use passphrases for your password manager master password, full-disk encryption passphrase, or any credential you must memorize. For everything else, use a shorter fully random password stored in your manager.',
        faq: [
            { q: 'How many words should my passphrase have?', a: 'At least four words for moderate security (~50-60 bits). Six words for high security (~75-90 bits). For a password manager master password, six words is the recommended minimum.' },
            { q: 'Should I add numbers and symbols to a passphrase?', a: 'Adding a number and symbol (e.g., "marble-sunset7-notebook!river") increases entropy by roughly 10-15 bits and makes the passphrase resistant to pure dictionary attacks. It is a worthwhile addition for minimal memorability cost.' },
            { q: 'Is a passphrase stronger than a regular password?', a: 'Per character, no — passphrases have lower entropy density. But a 6-word passphrase (~77 bits) that you can actually remember and type correctly is far more practical than a 12-character random string (~79 bits) that you will write on a sticky note.' },
            { q: 'What word list should passphrases use?', a: 'The EFF Diceware list (7,776 words) is the standard. Each word contributes ~12.9 bits of entropy. Avoid using common phrases, song lyrics, quotes, or personally meaningful words — the words must be randomly selected.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'pronounceable',
        seoTitle:       'Pronounceable Password Generator — Easy to Say Passwords | ToolKit',
        seoH1:          'Pronounceable Password Generator',
        seoDescription: 'Generate random passwords that are easy to pronounce and communicate verbally. Ideal for phone support and shared access. Free, browser-based, no signup.',
        intro:          'Sometimes a password needs to be communicated verbally — reading it to someone over the phone, dictating it to a colleague during setup, or sharing a temporary access code in a meeting. Random strings like "xK#9mQ$2" are nearly impossible to communicate accurately without the NATO phonetic alphabet. Pronounceable passwords solve this by using alternating consonant-vowel patterns that form syllable-like structures — "kobami", "luseta", "wopind" — while remaining random and unpredictable. Each syllable is selected randomly, not from a dictionary, so the passwords do not contain real words that could be guessed. This generator creates passwords with pronounceable patterns using mixed character types for the best balance of verbal communication and security.',
        faq: [
            { q: 'When should I use a pronounceable password?', a: 'When the password must be communicated verbally: phone support access codes, temporary passwords given in person, shared WiFi passwords told to guests, or any situation where someone needs to type what you say aloud.' },
            { q: 'Is a pronounceable password less secure?', a: 'Somewhat — pronounceable patterns reduce the character space compared to fully random strings. A 16-character pronounceable password has less entropy than a 16-character random one. Compensate by using longer passwords (20+ characters) when pronounceability is required.' },
            { q: 'Can pronounceable passwords contain numbers and symbols?', a: 'Yes. Adding a digit or symbol between pronounceable syllables (e.g., "koba4mi-luse") maintains verbal communication ability while increasing entropy. This generator mixes character types within pronounceable structures.' },
            { q: 'How is this different from a passphrase?', a: 'A passphrase uses real dictionary words ("marble-sunset-river"). A pronounceable password uses syllable-like patterns that are not real words ("kobami-luseta"). Pronounceable passwords are shorter but less memorable than passphrases.' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'for-kids',
        seoTitle:       'Password Generator for Kids — Safe & Simple Passwords | ToolKit',
        seoH1:          'Password Generator for Kids',
        seoDescription: 'Generate safe, simple passwords for children\'s accounts. Easy to type, meets school requirements. Free, browser-based, no data stored.',
        intro:          'Children need passwords for school platforms, educational games, and supervised email accounts — but they cannot manage the same complexity adults use. A child\'s password needs to be simple enough to type independently (especially for younger kids who are still learning the keyboard), easy to remember without writing it down in an insecure place, and strong enough to meet the school or platform\'s requirements. This generator defaults to 10 characters with uppercase, lowercase, and numbers — no symbols, since young children often struggle to locate symbol keys. For older children (12+), consider enabling symbols and increasing length to 12-14 characters. Parents should store children\'s passwords in their own password manager and supervise account access appropriate to the child\'s age.',
        faq: [
            { q: 'How long should a child\'s password be?', a: 'For ages 6-9, 8-10 characters without symbols is practical. For ages 10-12, 10-12 characters. For teenagers, the same as adults — 14-16 characters with full complexity. Adjust based on typing ability and the sensitivity of the account.' },
            { q: 'Should children\'s passwords include symbols?', a: 'For young children (under 10), no — symbols are hard to find on the keyboard and lead to frustration and login failures. For older children and teenagers, gradually introduce symbols as their typing skills improve.' },
            { q: 'Should I manage my child\'s passwords?', a: 'Yes, at least until they are mature enough to use a password manager independently (typically age 13+). Store their passwords in your own manager, and teach them about password security as they grow older.' },
            { q: 'Is it okay for children to reuse passwords?', a: 'Ideally no, but practically, young children may need a single password for multiple school platforms to avoid confusion. As they mature, transition to unique passwords per account with a password manager.' },
        ],
        defaults: { length: 10, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'for-work',
        seoTitle:       'Work Password Generator — Corporate & Enterprise Passwords | ToolKit',
        seoH1:          'Work & Corporate Password Generator',
        seoDescription: 'Generate passwords meeting corporate security policies. At least one uppercase, one number, one symbol. Compliant with enterprise requirements. Free, browser-based.',
        intro:          'Corporate environments typically enforce strict password policies: minimum 12-16 characters, at least one uppercase letter, one lowercase letter, one digit, and one symbol, with expiration every 60-90 days (though NIST now advises against forced rotation). These requirements exist because a single compromised employee account can give attackers access to internal networks, customer data, and intellectual property. Many enterprises use Active Directory, Okta, or similar identity providers that enforce these policies at the system level — your password will be rejected if it does not meet every requirement. This generator defaults to 16 characters with all types enabled, meeting or exceeding the policies of most enterprise environments. If your company uses single sign-on (SSO), you may only need this for your primary domain password, with SSO handling everything else.',
        faq: [
            { q: 'Why do corporate password policies seem so strict?', a: 'Businesses face regulatory requirements (SOC 2, HIPAA, PCI DSS, GDPR) that mandate strong access controls. A single compromised account can lead to data breaches costing millions. The policies exist to establish a security baseline across all employees.' },
            { q: 'Should I still follow the 90-day rotation policy?', a: 'Follow your company\'s policy even if NIST advises against forced rotation. IT security teams set policies based on the organization\'s specific risk profile and compliance requirements. If you want to advocate for change, share the NIST SP 800-63B guidelines with your IT team.' },
            { q: 'Can I use a password manager at work?', a: 'Many companies provide enterprise password managers (1Password Business, LastPass Enterprise, Dashlane Business). If your company offers one, use it. If not, ask your IT department — using an unauthorized tool may violate security policy.' },
            { q: 'What about single sign-on (SSO)?', a: 'SSO reduces the number of passwords you need — you log in once to your identity provider and access all connected applications. Your SSO password becomes critical: make it the strongest password in your work life (20+ characters).' },
        ],
        defaults: { length: 16, uppercase: true, lowercase: true, numbers: true, symbols: true },
    },
    {
        slug:           'for-temporary',
        seoTitle:       'Temporary Password Generator — Short-Lived Access Codes | ToolKit',
        seoH1:          'Temporary Password Generator',
        seoDescription: 'Generate temporary passwords for short-term access. Ideal for guest accounts, one-time logins, and initial setup. Free, browser-based, no signup.',
        intro:          'Temporary passwords serve a specific purpose: granting short-lived access that will be changed or revoked soon. Common scenarios include initial account setup (where the user must change the password on first login), guest access to a WiFi network or shared system, vendor or contractor access for a limited engagement, and one-time passwords for identity verification. Temporary passwords can be shorter than permanent ones because their exposure window is limited — an 8-10 character password that exists for only 24 hours has a much smaller attack surface than one used for months. This generator defaults to 10 characters with letters and numbers (no symbols for easy verbal communication). Always set an expiration on temporary credentials and revoke them as soon as the access period ends.',
        faq: [
            { q: 'How long should a temporary password be?', a: '8-12 characters is usually sufficient for passwords that expire within 24-48 hours. The limited time window reduces the attack surface. For temporary access lasting weeks, use 14-16 characters.' },
            { q: 'Should temporary passwords include symbols?', a: 'Often no — temporary passwords are frequently communicated verbally or typed manually from a printout. Symbols make this harder and cause more support calls. Letters and numbers are easier to communicate accurately.' },
            { q: 'Should I force a password change after first login?', a: 'Yes, for initial setup passwords. This ensures only the account owner knows the permanent password. For guest access, it is not necessary — just revoke the credential when access is no longer needed.' },
            { q: 'How should I send a temporary password?', a: 'Ideally through a separate channel from the username — send the username by email and the password by SMS, or use a secure messaging app. Never send both in the same email.' },
        ],
        defaults: { length: 10, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'pin-code',
        seoTitle:       'PIN Code Generator — Random 4-8 Digit PINs | ToolKit',
        seoH1:          'PIN Code Generator',
        seoDescription: 'Generate random PIN codes (4-8 digits). For bank cards, phone locks, safes, and access systems. Cryptographically random. Free, browser-based.',
        intro:          'PINs — Personal Identification Numbers — are everywhere: bank cards, phone lock screens, safe combinations, building access panels, SIM cards, and parental controls. A PIN is designed to be short and fast to enter, relying on rate limiting (account lockout after failed attempts) rather than length for security. The most common PIN length is 4 digits (10,000 combinations), but 6-digit PINs (1,000,000 combinations) are increasingly standard for phones and financial services. The critical rule for PINs is randomness: studies show that the most common 4-digit PIN is "1234" (used by over 10% of people), followed by "1111", "0000", and birth years. A randomly generated PIN avoids these predictable patterns entirely. This generator creates random numeric PINs using the Web Crypto API — the same cryptographic randomness used for full passwords.',
        faq: [
            { q: 'Should I use a 4-digit or 6-digit PIN?', a: 'Use 6 digits whenever the system allows it. A 6-digit PIN has 1,000,000 combinations versus 10,000 for a 4-digit PIN — that is 100 times harder to guess. Most modern phones and banking apps support 6-digit PINs.' },
            { q: 'What PINs should I avoid?', a: 'Never use: 1234, 1111, 0000, 1212, your birth year (1990, 1985, etc.), your birthday (0315 for March 15), repeated digits (7777), or sequential patterns (4567). These are the first combinations attackers try.' },
            { q: 'Is a PIN secure enough for my phone?', a: 'With rate limiting (increasing delays after wrong attempts and wipe after 10 failures), a random 6-digit PIN is secure for a phone. For maximum security, use a full alphanumeric password instead of a PIN.' },
            { q: 'Can I use the same PIN for my bank card and phone?', a: 'No — if someone observes you entering your phone PIN (shoulder surfing), they should not also have your bank PIN. Use different PINs for different purposes, and store them in a password manager if needed.' },
        ],
        defaults: { length: 6, uppercase: false, lowercase: false, numbers: true, symbols: false },
    },
    {
        slug:           'for-database',
        seoTitle:       'Database Password Generator — MySQL, PostgreSQL & MongoDB | ToolKit',
        seoH1:          'Database Password Generator',
        seoDescription: 'Generate strong passwords for MySQL, PostgreSQL, MongoDB and other databases. Avoids problematic characters. Free, browser-based, no data stored.',
        intro:          'Database passwords protect your most valuable asset — your data. A compromised database password gives an attacker direct access to every record, bypassing all application-level security. Database passwords have unique requirements: they are often stored in configuration files, environment variables, or connection strings, where certain characters can cause parsing issues. Single quotes, double quotes, backslashes, semicolons, and the percent sign can break connection strings in many frameworks. This generator defaults to 32 characters with alphanumeric characters — long enough for maximum security while avoiding the special characters that commonly cause configuration headaches. For databases, the password is always copy-pasted from a vault or configuration management system, never typed manually, so extreme length has zero usability cost.',
        faq: [
            { q: 'Why are database passwords different from regular passwords?', a: 'Database passwords are stored in config files, environment variables, and connection strings where special characters like quotes, backslashes, and semicolons can cause parsing errors. They are also never typed manually, so they can be much longer without usability concerns.' },
            { q: 'How long should a database password be?', a: 'At least 32 characters. Since database passwords are always copy-pasted or stored in config, there is no reason to use anything shorter. MySQL supports up to 32 characters for native auth, PostgreSQL has no practical limit.' },
            { q: 'Which characters should I avoid in database passwords?', a: 'Avoid single quotes (\'), double quotes ("), backslashes (\\), semicolons (;), percent signs (%), and at signs (@) — these can break connection strings, SQL queries, or URL-format connection URIs. Alphanumeric with underscores and hyphens is safest.' },
            { q: 'How should I store database passwords?', a: 'Use environment variables, a secrets manager (AWS Secrets Manager, HashiCorp Vault, GCP Secret Manager), or encrypted configuration. Never hardcode database passwords in source code or commit them to version control.' },
        ],
        defaults: { length: 32, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
    {
        slug:           'for-ssh',
        seoTitle:       'SSH Passphrase Generator — Secure Your SSH Keys | ToolKit',
        seoH1:          'SSH Key Passphrase Generator',
        seoDescription: 'Generate strong passphrases for SSH private keys. Protect your server access with a secure passphrase. Free, browser-based, no data stored.',
        intro:          'An SSH key passphrase encrypts your private key file — if someone steals the file (from a backup, a compromised laptop, or a stolen drive), they cannot use it without the passphrase. Without a passphrase, anyone with your private key file has instant access to every server it is authorized for. The passphrase should be long enough to resist offline brute-force attacks against the key file encryption (typically AES-128 or AES-256). Since you type this passphrase whenever you load the key (unless using an SSH agent), it needs to be both strong and typeable. This generator defaults to 20 characters with letters and numbers — a practical balance between security and the frequent typing required. If you use an SSH agent that caches the unlocked key, you can use a longer, more complex passphrase since you only type it once per session.',
        faq: [
            { q: 'Do I really need a passphrase on my SSH key?', a: 'Yes. An unprotected private key is equivalent to writing your password in a plain text file. Anyone who obtains the file — through a backup breach, stolen laptop, or malware — has full access to your servers.' },
            { q: 'How long should an SSH passphrase be?', a: 'At least 16-20 characters. The passphrase protects against offline attacks on the key file, so it needs to be strong enough to resist GPU-accelerated cracking. 20 characters with mixed types provides ~119-131 bits of entropy.' },
            { q: 'Can I use an SSH agent to avoid typing it repeatedly?', a: 'Yes. ssh-agent caches the decrypted key in memory for the duration of your session. You type the passphrase once when loading the key, then connect to servers without re-entering it. On macOS, the Keychain can store it permanently.' },
            { q: 'What if I forget my SSH passphrase?', a: 'There is no recovery mechanism — the passphrase is the encryption key for the private key file. You would need to generate a new SSH key pair and add the new public key to your servers. Store the passphrase in a password manager as backup.' },
        ],
        defaults: { length: 20, uppercase: true, lowercase: true, numbers: true, symbols: false },
    },
];